from Old_Jeu.Systeme.Constantes_magies.Constantes_absorption import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_avalanche import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_blizzard import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_bombes import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_boost import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_boule_de_feu import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_brasier import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_cecite import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_celerite import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_confusion import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_dopage import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_eclair_noir import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_explosion_de_mana import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_faiblesse import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_flamme import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_fleche_de_glace import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_force import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_immunite import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_instakill import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_investissement import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_jet_de_mana import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_laser import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_multi_boost import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_multi_soin import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_neige import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_obscurite import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_ombre_furtive import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_perte_de_pm import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_perte_de_pv import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_petite_secousse import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_poches_trouees import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_poing_ardent import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_poing_magique import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_poing_sombre import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_protection_sacree import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_purification import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_reanimation import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_renforcement import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_reserve import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_resurection import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_rocher import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_rouille import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_sable import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_secousse import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_soin import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_soin_auto import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_soin_superieur import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_soin_zone import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_teleportation import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_tenebre import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_vision import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_vitalite import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_vitesse import *
from Old_Jeu.Systeme.Constantes_magies.Constantes_volcan import *
