global REPLIQUES_PAUME
REPLIQUES_PAUME = {
    "dialogue1phrase1":"Quelle chance, il y a quelqu'un ici !",
    "dialogue1reponse1.1":"Bonjour.",
    "dialogue1reponse1.2":"Je ne fais que passer, au-revoir.",
    "dialogue1phrase1.1":"Où est-ce que tu vas comme ça ?",
    "dialogue1reponse1.1.1":"Je cherche la sortie.",
    "dialogue1phrase1.1.1":"Ces grottes sont un vrai labyrinthe, tu risquerais de te perdre !",
    "dialogue1reponse1.1.1.1":"Je vais y aller quand même.",
    "dialogue1reponse1.1.1.2":"Tu connais un autre chemin ?",
    "dialogue1phrase1.1.1.1":"Ton courage est impressionnant ! Moi, je suis ici depuis plusieurs jours.",
    "dialogue1phrase1.1.1.2":"Non...",
    "dialogue1reponse1.1.1.2.1":"Alors je n'ai pas d'autre choix que d'y aller",
    "dialogue1reponse1.1.1.1.1":"Tu peux venir avec moi, si ça te rassure.",
    "dialogue1reponse1.1.1.1.2":"Tu es vraiment pathétique.",
    "dialogue1phrase1.1.1.1.1":"Merci beaucoup ! N'hésite pas à me demander si tu as besoin de quelque-chose.",
    "dialogue1reponse1.1.1.1.1.1":"Je ferais appel à toi.",
    "dialogue1phrase1.1.1.1.1.1":"Au fait, tu peux courir avec R, mais évite de me perdre de vue s'il te plaît !",
    "dialogue1reponse1.1.1.1.1.1.1":"Merci du conseil",
    "dialogue2phrase1":"Le gobelin est mort !",
    "dialogue2reponse1.1":"Oui ! Mais il nous a blessés...",
    "dialogue2reponse1.2":"Pff, trop facile !",
    "dialogue2reponse1.3":"Je n'ai pas tout compris...",
    "dialogue2phrase1.1":"Ne t'inquiète pas, nos blessures se soignent avec le temps.",
    "dialogue2reponse1.1.1":"Ah, tu me rassures. En route alors !",
    "dialogue2reponse1.1.2":"Ouf ! Mais, je ne suis pas sûr d'avoir compris tout ce qui s'est passé.",
    "dialogue2phrase1.3":"Qu'est-ce que tu n'as pas compris ?",
    "dialogue2reponse1.3.1":"Comment est-ce que le gobelin est mort ?",
    "dialogue2reponse1.3.2":"C'était quoi, tous les trucs qu'on voyait ?",
    "dialogue2reponse1.3.3":"Pourquoi est-ce qu'il reste quelque chose ?",
    "dialogue2phrase1.3.1":"Il avait une barre rouge au-dessus de la tête, comme toi et moi avons une barre verte. Cette barre représente ses PVs, et chacune de nos attaques lui a fait perdre des PVs. Quand ses PVs ont atteint 0, il est mort.",
    "dialogue2phrase1.3.2":"Les marques marrons représentaient les attaques. Il y avait aussi des points rouges à chaque fois que quelqu'un se faisait blesser.",
    "dialogue2phrase1.3.2/peureuse":"Les marques marrons représentaient les attaques. Il y avait aussi des points rouges à chaque fois que quelqu'un se faisait blesser. Et s'il y avait des espèces de cercles oranges sous nos pieds, c'étaient les magies de boost lancés par notre coéquipière. Tu as peut-être pu voir qu'elle-même avait un cercle bleu à chaque fois qu'elle lançait une magie.",
    "dialogue2phrase1.3.3":"Le corps du gobelin n'allait pas disparaître ! Son cadavre est toujours là. Il y a aussi les items qu'il transportait, en l'occurence son équippement.",
    "dialogue2reponse1.3.1.1":"Merci, c'est tout ce que je voulais savoir !",
    "dialogue2reponse1.3.1.2":"Il y a autre chose que je n'ai pas compris.",
    "dialogue3phrase1":"Il était coriace, celui-là !",
    "dialogue3reponse1.1":"C'est peu de le dire ! Qu'est-ce que c'était que ces attaques à distance !?",
    "dialogue3reponse1.2":"Mais non, c'était facile !",
    "dialogue3phrase1.1":"Aucune idée. Peut-être de la magie ?",
    "dialogue3reponse1.1.1":"J'aimerais pouvoir faire de la magie moi aussi...",
    "dialogue3reponse1.1.2":"Une tactique de faible !",
    "dialogue3phrase1.1.1":"Ça semble puissant comme ça, mais les mages sont toujours en train de manquer de mana...",
    "dialogue3phrase1.1.2":"En tous cas, ce n'était pas suffisant pour nous vaincre.",
    "dialogue3reponse1.1.1.1":"Et nous de PVs, chacun ses problèmes. Bon, on y retourne ?",
    "dialogue3reponse1.1.2.1":"Bien dit ! C'est pas tout ça, retournons explorer.",
    "dialogue4phrase1":"Est-ce que tu vois ces portes dans les murs autour de toi ?",
    "dialogue4reponse1.1":"Oui.",
    "dialogue4reponse1.2":"Ces barres oranges ?",
    "dialogue4reponse1.3":"Évidemment, je ne suis pas aveugle !",
    "dialogue4phrase1.1":"Il te faut des clés pour les ouvrir.",
    "dialogue4phrase1.2":"C'est ça. Il te faut des clés pour les ouvrir.",
    "dialogue4reponse1.1.1":"Des clés ? Où est-ce que je peux les trouver ?",
    "dialogue4phrase1.1.1":"Par terre, après avoir tué un monstre par exemple. Ramasse-les avec la touche M.",
    "dialogue4reponse1.1.1.1":"Ok, je regarderai autour de moi.",
    "dialogue5phrase1":"Tu as remarqué le portail de téléportation ?",
    "dialogue5reponse1.1":"Oui.",
    "dialogue5reponse1.2":"Cet espèce de mur bleu ?",
    "dialogue5reponse1.3":"Évidemment ! Maintenant laisse-moi chercher la sortie.",
    "dialogue5phrase1.1":"Celui-ci est un portail à double-sens, heureusement.",
    "dialogue5phrase1.2":"C'est ça.",
    "dialogue5reponse1.1.1":"J'espère que je ne tomberai pas dans un tel piège.",
    "dialogue5reponse1.1.2":"Il y en a qui ne passent que dans un sens ?",
    "dialogue5reponse1.1.3":"Bah, je n'ai qu'à tuer tout ce qu'il y a au-delà. Pourquoi revenir en arrière ?",
    "dialogue5reponse1.2.1":"",
    "dialogue5phrase1.1.1":"Ici, tu risques plutôt d'avoir des problèmes à cause du manque de place.",
    "dialogue5phrase1.1.2":"Il y en a aussi qui sont invisibles...",
    "dialogue5phrase1.1.3":"Si tu tombes dans un cul-de-sac, ça peut vite devenir compliqué... même sans portail à sens unique en fait, dans des petits espaces comme ici.",
    "dialogue5reponse1.1.1.1":"En quoi le manque de place est-il dérangeant ?",
    "dialogue5reponse1.1.1.2":"C'est vrai. D'ailleurs, il faut que j'aille donner quelques consignes. Je t'appellerais à nouveau à l'occasion.",
    "dialogue5reponse1.1.2.1":"Ugh. Pourquoi faut-il qu'il y ait de tels pièges...",
    "dialogue5reponse1.1.3.1":"Ha, vraiment ? On s'en moque, que ça soit petit ici.",
    "dialogue5reponse1.1.3.2":"Mais oui, bien sûr. J'ai plus important à faire, j'y vais.",
    "dialogue5phrase1.1.1.1":"Dans des espaces aussi petits, c'est facile d'être bloqué par d'autres. Si, par exemple, tu cherches à fuir un monstre et tu te retrouves bloqué face à quelqu'un qui va au corps-à-corps, tu peux en mourir.",
    "dialogue5phrase1.1.3.1":"Pas vraiment, non. Si, par exemple, tu cherches à fuir un monstre et tu te retrouves bloqué face à quelqu'un qui va au corps-à-corps, tu peux en mourir.",
    "dialogue5reponse1.1.1.1":"Je vois... C'est en effet plus difficile de se contourner.",
    "dialogue5phrase1.1.1.1":"Cependant, quelques consignes peuvent aider à organiser les déplacements.",
    "dialogue5reponse1.1.1.1.1":"Des consignes ? Comment je fais ça ?",
    "dialogue5reponse1.1.1.1.2":"Certes. Justement, je vais aller en donner avant de progresser plus loin.",
    "dialogue5phrase1.1.1.1.1":"Tu sais comment communiquer ?",
    "dialogue5reponse1.1.1.1.1.1":"Euh... non.",
    "dialogue5reponse1.1.1.1.1.2":"Oui, l'épéiste que j'ai rencontré juste après ma chute m'a expliqué.",
    "dialogue5phrase1.1.1.1.1.1":"Lorsque tu es à côté de quelqu'un, appuie sur la touche Espace pour dialoguer. Il ne faut pas que ton curseur de zone soit sur un élément séléctionable.",
    "dialogue5phrase1.1.1.1.1.2":"Après avoir commencé le dialogue, c'est tout simple. Tu dois choisir de quoi tu veux discuter, et ce que tu veux demander.",
    "dialogue5reponse1.1.1.1.1.1.1":"Oulà... Rappelle-moi cette histoire de zones ?",
    "dialogue5reponse1.1.1.1.1.1.2":"Ah, oui. Je m'en souviens maintenant.",
    "dialogue5reponse1.1.1.1.1.2.1":"Je peux demander tout ce que je veux ?",
    "dialogue5phrase1.1.1.1.1.1.1":"Tu dois avoir un curseur rouge quelque part sur ton écran. Tu peux le déplacer avec les touches A, E, Z, S, Q et D.",
    "dialogue5phrase1.1.1.1.1.2.1":"Presque. Mais pas sûr que tu sois exaucé...",
    "dialogue5reponse1.1.1.1.1.1.1.1":"J'ai beau appuyer, il ne se passe rien...",
    "dialogue5reponse1.1.1.1.1.2.1.1":"Ah... Zut.",
    "dialogue5phrase1.1.1.1.1.1.1.1":"Oui, les touches de zones ne fonctionnent pas pendant les dialogues.",
    "dialogue5phrase1.1.1.1.1.2.1.1":"Dans le cas des salles peu spacieuses, tu pourrais demander aux supports de rester à l'écart et à l'abri, puisqu'ils peuvent aider à distance. Ensuite, tu peux les rappeler de loin.",
    "dialogue5reponse1.1.1.1.1.1.1.1.1":"C'est donc pour ça.",
    "dialogue5reponse1.1.1.1.1.2.1.1.1":"Attends... les rappeler de loin ? Comment je fais ça ?",
    "dialogue5phrase1.1.1.1.1.1.1.1.1":"A et E permettent de changer de niveau, c'est-à-dire d'entrer dans les sous-menus et en sortir. Le menu le plus global est composé des trois zones d'affichages : le menu de gauche ; le carré central ; et l'affichage de droite. Tu peux passer de l'une à l'autre avec les touches Q et D, qui correspondent aux déplacements dans les listes horizontales.",
    "dialogue5phrase1.1.1.1.1.2.1.1.1":"Tu sais utiliser les touches de zones ?",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1":"Et je suppose que Z et S me déplacent dans les listes verticales... Et ensuite, une fois que j'ai sélectionné, par exemple, la zone de gauche ?",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.1":"Euh... un rappel ne fera pas de mal.",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.2":"Oui. Dans quelle zone est-ce que je dois aller ?",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1":"Tu peux utiliser la touche A pour entrer dans la zone de gauche, qui comprend trois sous-zones : en haut, tes informations avec tes points de vie et de mana ;  en dessous, ton iventaire ; et enfin ta classe, qui répertorie tes sous-classes et tes skills.",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.1":"Tu sais utiliser les touches de zones ?",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.2":"À gauche, dans la liste du haut qui répertorie tes alliés. Si tu appuies sur Espace, l'allié sélectionné viendra te voir de lui-même. Et si c'est toi qui est sélectionné, nous viendrons tous te voir. Enfin, à condition de savoir venir jusqu'à toi.",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1":"Pour rentrer dans l'inventaire par exemple, c'est encore A ?",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.1.1":"Tu dois avoir un curseur rouge quelque part sur ton écran. Tu peux le déplacer avec les touches A, E, Z, S, Q et D.",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.2.1":"Je vois... merci pour toutes ces explications !",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1.1":"Exactement. L'inventaire est lui-même organisé en catégories, qui contiennent les listes d'items. Une fois que tu as sélectionné un item, tu peux appuyer sur Espace pour l'utiliser, si c'est une potion, un parchemin ou un équippement. Puis tu peux ressortir de chaque niveau en appuyant sur E.",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.1.1":"J'ai beau appuyer, il ne se passe rien...",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1.1":"Donc si je veux utiliser un élément sélectionné avec les touches de zones, j'appuie sur Espace. Et quand je suis en dehors des zones, Espace me permet de dialoguer avec quelqu'un à côté de moi ?",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.1.1.1":"Oui, les touches de zones ne fonctionnent pas pendant les dialogues.",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1.1.1":"Pas que. Tu peux aussi interagir avec certains objets.",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.1.1.1":"C'est donc pour ça.",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1.1.1":"Hum... ça fait beaucoup pour une seule touche... mais revenons au dialogue.",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.1.1.1.1":"A et E permettent de changer de niveau, c'est-à-dire d'entrer dans les sous-menus et en sortir. Le menu le plus global est composé des trois zones d'affichages : le menu de gauche ; le carré central ; et l'affichage de droite. Tu peux passer de l'une à l'autre avec les touches Q et D, qui correspondent aux déplacements dans les listes horizontales.",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1.1.1.1":"Après avoir commencé le dialogue, c'est tout simple. Tu dois choisir de quoi tu veux discuter, et ce que tu veux demander.",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.1.1.1.1":"Et je suppose que Z et S me déplacent dans les listes verticales... Et ensuite, une fois que j'ai sélectionné, par exemple, la zone de gauche ?",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Je peux demander tout ce que je veux ?",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.1.1.1.1.1":"Tu peux utiliser la touche A pour entrer dans la zone de gauche, qui comprend trois sous-zones : en haut, tes informations avec tes points de vie et de mana ;  en dessous, ton iventaire ; et enfin ta classe, qui répertorie tes sous-classes et tes skills.",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Presque. Mais pas sûr que tu sois exaucé...",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.1.1.1.1.1":"Pour rentrer dans l'inventaire par exemple, c'est encore A ?",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Ah... Zut.",
    "dialogue5reponse1.1.1.1.1.2.1.1.1.1.1.1.1.1.1":"Exactement. L'inventaire est lui-même organisé en catégories, qui contiennent les listes d'items. Une fois que tu as sélectionné un item, tu peux appuyer sur Espace pour l'utiliser, si c'est une potion, un parchemin ou un équippement. Puis tu peux ressortir de chaque niveau en appuyant sur E.",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Dans le cas des salles peu spacieuses, tu pourrais demander aux supports de rester à l'écart et à l'abri, puisqu'ils peuvent aider à distance. Ensuite, tu peux les rappeler de loin.",
    "dialogue5phrase1.1.1.1.1.2.1.1.1.1.1.1.1.1.1":"Donc si je veux utiliser un élément sélectionné avec les touches de zones, j'appuie sur Espace. Et pour rappeler mes alliés de loin, dans quelle zone je dois aller ?",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Attends... les rappeler de loin ? Comment je fais ça ?",
    "dialogue5phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Avec les touches de zone !",
    "dialogue5reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Encore ? Et donc, dans quelle zone je dois aller ?",
    "dialogue-1phrase1":"Je peux me rendre utile ?",
    "dialogue-1reponse1.1":"Va quelque part.",
    "dialogue-1reponse1.2":"J'aimerais parler avec toi.",
    "dialogue-1reponse1.3":"C'est bon, merci.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Désolé, je... je n'ai vraiment pas le courage d'y aller tout seul. Je peux me rendre utile autrement ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.1":"Ok. Je peux faire autre chose ?",
    "dialogue-1phrase1.1.1.2":"C'est noté. Je peux faire autre chose ?",
    "dialogue-2phrase1":"Quoi ?",
    "dialogue-2reponse1.1":"Rien !",
    "dialogue-2reponse1.2":"Tu veux que je t'aide à sortir d'ici ?",
    "dialogue-2reponse1.3":"Je voudrais m'excuser pour ce que j'ai dit.",
    "dialogue-2phrase1.2":"Non merci, je préfère rester bloqué que demander ton aide !",
    "dialogue-2phrase1.3":"... Bon, je te pardonne.",
    "dialogue-2reponse1.2.1":"Eh bien reste-ici !",
    "dialogue-2reponse1.3.1":"Du coup, on va à la sortie ?",
    "dialogue-2phrase1.3.1":"Ok, montre-moi le chemin.",
    "dialogue-2reponse1.3.1.1":"Tache de ne pas te perdre.",
    "dialogue-2reponse1.3.1.2":"Fais-moi confiance !"} #À compléter avec plus de répliques
