# global REPLIQUES_RECEPTIONNISTE
REPLIQUES_RECEPTIONNISTE ={
    "dialogue1phrase1":"Quelle chute ! Tu vas bien ? Tu peux m'entendre.",
    "dialogue1reponse1.1":"Oui...",
    "dialogue1phrase1.1":"Tu peux te lever ? Utilise les flèches directionnelles pour te diriger, et W pour marcher. Appuie sur Espace à côté de moi pour revenir me parler.",
    "dialogue1reponse1.1.1":"Merci pour ton aide.",
    "dialogue2phrase1":"Alors, ça va mieux ?",
    "dialogue2reponse1.1":"Oui, un peu. Où est-on ?",
    "dialogue2reponse1.2":"Je suis en pleine forme maintenant ! Où est-ce que je devrais aller ?",
    "dialogue2phrase1.1":"Dans le labyrinthe de [insérer le nom de la montagne/mine/caverne ici]. La sortie est gardée par un [insérer le nom du boss ici] que je n'ai pas réussi à vaincre.",
    "dialogue2reponse1.1.1":"Un [insérer le nom du boss ici] ? J'en ai croisé un là-haut, il m'a fait tomber ici.",
    "dialogue2reponse1.1.2":"La sortie ? Où ça ?",
    "dialogue2phrase1.1.1":"Heureusement que ton armure t'a protégé de la chute...",
    "dialogue2reponse1.1.1.1":"Et du coup, où est la sortie ?",
    "dialogue2phrase1.1.1.1":"Il y a un escalier au bout du couloir, à droite.",
    "dialogue2reponse1.1.1.1.1":"...",
    "dialogue-2phrase1":"Qu'est-ce qu'il y a ?",
    "dialogue-2reponse1.1":"Je ne trouve pas l'escalier.",
    "dialogue-2reponse1.2":"Il n'y a pas d'autre chemin ?",
    "dialogue-2reponse1.3":"Merci encore pour ton aide.",
    "dialogue-2phrase1.1":"Au bout du couloir, à droite.",
    "dialogue-2phrase1.2":"Il y a bien une porte tout à gauche, mais elle est fermée à clée.",
    "dialogue-2phrase1.3":"De rien.",
    "dialogue-2reponse1.2.1":"Tant pis. Je vais essayer l'escalier alors.",
    "dialogue-2phrase1.2.1":"Bon courage !",
    "dialogue-2reponse1.1.1":"..."} #À compléter avec plus de répliques
