global REPLIQUES_PEUREUSE
REPLIQUES_PEUREUSE = {
    "dialogue1phrase1":"Bonjour !",
    "dialogue1reponse1.1":"Salut...",
    "dialogue1reponse1.2":"Bonjour ma jolie.",
    "dialogue1phrase1.1":"",
    "dialogue1phrase1.2":"Ne me parle pas si familièrement.",
    "dialogue1reponse1.1.1":"...qu'est-ce que tu fais ici ?",
    "dialogue1reponse1.1.2":"...où est la sortie ?",
    "dialogue1reponse1.2.1":"Désolé...",
    "dialogue1reponse1.2.2":"Allez, fais pas ta timide...",
    "dialogue1phrase1.1.1":"Je voudrais continuer, mais il y a des monstres sur le chemin.",
    "dialogue1phrase1.1.2":"Tout en haut.",
    "dialogue1phrase1.2.2":"Sérieusement, t'es lourd ! J'ai déjà un copain, [insérer le nom du copain ici], alors arrête !",
    "dialogue1reponse1.1.1.1":"Tu veux que je les tue pour toi ?",
    "dialogue1reponse1.1.1.2":"Des monstres ? Ils sont dangereux ?",
    "dialogue1reponse1.1.2.1":"Pourquoi tu n'y vas pas ?",
    "dialogue1phrase1.1.1.1":"S'il te plaît !",
    "dialogue1phrase1.1.1.2":"Un peu. C'est surtout que je suis fragile...",
    "dialogue1phrase1.1.2.1":"Il y a des monstres sur le chemin.",
    "dialogue1reponse1.1.1.1.1":"Euh... comment on fait pour combattre ?",
    "dialogue1reponse1.1.1.1.2":"Laisse-moi faire.",
    "dialogue1reponse1.1.1.2.1":"Je vais essayer de les combattre.",
    "dialogue1reponse1.1.1.2.2":"Pff... les faibles n'ont qu'à mourir.",
    "dialogue1phrase1.1.1.1.1":"Tu peux donner un coup de pied au sol avec la touche P, je suppose.",
    "dialogue1phrase1.1.1.2.1":"Tu sais faire ?",
    "dialogue1reponse1.1.1.1.1.1":"Un coup de pied au sol ? Ça n'a pas l'air très efficace.",
    "dialogue1reponse1.1.1.1.1.2":"D'accord, je vais y aller.",
    "dialogue1reponse1.1.1.2.1.1":"Oui.",
    "dialogue1reponse1.1.1.2.1.2":"Euh, non...",
    "dialogue1phrase1.1.1.1.1.1":"Je suppose que tu pourrais utiliser ta lance avec X, mais vu son état ça sera encore moins efficace.",
    "dialogue1phrase1.1.1.1.1.2":"Je peux venir avec toi ?",
    "dialogue1reponse1.1.1.1.1.2.1":"Oui, viens.",
    "dialogue1reponse1.1.1.1.1.2.2":"Non, tu ne ferais que me gêner.",
    "dialogue2phrase1":"Ouf, ce gobelin est mort !",
    "dialogue2reponse1.1":"Oui ! Mais il nous a blessés...",
    "dialogue2reponse1.2":"Pff, trop facile !",
    "dialogue2reponse1.3":"Je n'ai pas tout compris...",
    "dialogue2phrase1.1":"Heureusement, nos blessures se soignent avec le temps.",
    "dialogue2reponse1.1.1":"Ah, tu me rassures. En route alors !",
    "dialogue2reponse1.1.2":"Ouf ! Mais, je ne suis pas sûr d'avoir compris tout ce qui s'est passé.",
    "dialogue2phrase1.3":"Qu'est-ce que tu n'as pas compris ?",
    "dialogue2reponse1.3.1":"Comment est-ce que le gobelin est mort ?",
    "dialogue2reponse1.3.2":"C'était quoi, tous les trucs qu'on voyait ?",
    "dialogue2reponse1.3.3":"Pourquoi est-ce qu'il reste quelque chose ?",
    "dialogue2phrase1.3.1":"Il avait une barre rouge au-dessus de la tête, comme toi et moi avons une barre verte. Cette barre représente ses PVs, et chacune de tes attaques lui a fait perdre des PVs. Quand ses PVs ont atteint 0, il est mort.",
    "dialogue2phrase1.3.2":"Les marques marrons représentaient les attaques. Il y avait aussi des points rouges à chaque fois que quelqu'un se faisait blesser. Et s'il y avait des espèces de cercles oranges sous tes pieds, c'étaient mes magies de boost. Tu as peut-être pu voir que j'avais moi-même un cercle bleu à chaque fois que je lançais une magie.",
    "dialogue2phrase1.3.3":"Le corps du gobelin n'allait pas disparaître ! Son cadavre est toujours là. C'est dégoutant, mais il y a aussi les items qu'il transportait, en l'occurence son équippement.",
    "dialogue2reponse1.3.1.1":"Merci, c'est tout ce que je voulais savoir !",
    "dialogue2reponse1.3.1.2":"Il y a autre chose que je n'ai pas compris.",
    "dialogue3phrase1":"Ouf ! Il était coriace, celui-là !",
    "dialogue3reponse1.1":"C'est peu de le dire ! Qu'est-ce que c'était que ces attaques à distance !?",
    "dialogue3reponse1.2":"Mais non, c'était facile !",
    "dialogue3phrase1.1":"De la magie. Heureusement qu'il ne peut plus s'en servir quand il tombe à court de mana.",
    "dialogue3reponse1.1.1":"Tu es une magicienne, non ? Tu peux utiliser ce genre de sorts ?",
    "dialogue3reponse1.1.2":"Effectivement, ce serait infernal sinon !",
    "dialogue3phrase1.1.1":"Je suis juste une magicienne de soutien, je n'ai pas de sorts d'attaque. Mais je peux doubler tes dégats, et je n'ai même pas besoin de me mettre en danger en première ligne, c'est pas génial ?",
    "dialogue3reponse1.1.1.1":"C'est comme si j'étais deux fois plus nombreux ! Merci pour ton aide.",
    "dialogue3reponse1.1.1.2":"Pff, inutile...",
    "dialogue4phrase1":"Nous nous rapprochons du camp gobelin, il serait bien que je t'explique quelques trucs sur les monstres.",
    "dialogue4reponse1.1":"Oui, volontiers.",
    "dialogue4reponse1.2":"C'est gentil de proposer, mais je n'ai pas besoin d'aide.",
    "dialogue4reponse1.3":"Tu me prends pour un débutant ? Tu crois que je ne connais pas les monstres ?",
    "dialogue4phrase1.1":"Les monstres sont très différents les uns des autres, aussi bien par leurs comportements que par leurs capacitées.",
    "dialogue4phrase1.2":"D'accord, bonne chance.",
    "dialogue4phrase1.3":"Ne viens pas te plaindre si tu meurs !",
    "dialogue4reponse1.1.1":"Donc, ils ne vont pas tous attendre sans bouger comme celui de l'étage précédent ?",
    "dialogue4reponse1.1.2":"Leurs capacitées ? Tu veux dire leur puissance de combat ?",
    "dialogue4reponse1.2.1":"",
    "dialogue4phrase1.1.1":"Exactement. Celui-là était une sentinelle, qui ne bougent que quand il aperçoit un ennemi.",
    "dialogue4phrase1.1.2":"Entre autre, mais je pensais plutôt aux capacités comme le soin, ou les attaques magiques.",
    "dialogue4reponse1.1.1.1":"Attendre qu'on vienne à eux est donc plutôt une exception ?",
    "dialogue4reponse1.1.1.2":"Est-ce qu'il y a d'autres monstres que des gobelins ici ?",
    "dialogue4reponse1.1.2.1":"Ils peuvent même utiliser des magies de soin ?",
    "dialogue4phrase1.1.1.1":"Oui. C'est encore plus rare chez les monstres non-humanoïdes comme les slimes.",
    "dialogue4phrase1.1.1.2":"Il y a les gobelins, les orcs, les slimes, les ombriuls... certains ne sont pas hostiles aux humains, et ne combattront que si on les provoque.",
    "dialogue4phrase1.1.2.1":"Les humanoïdes comme les gobelins comptent des mages très variés dans leurs rangs.",
    "dialogue4reponse1.1.1.1.1":"Il existe différentes espèces de monstres ?",
    "dialogue4reponse1.1.1.1.2":"Et qu'est-ce que tu disais sur leurs capacités ?",
    "dialogue4reponse1.1.2.1.1":"Donc ils ont des rôles spécifiques...",
    "dialogue4reponse1.1.2.1.2":"Et les monstres non-humanoïdes ?",
    "dialogue4phrase1.1.1.1.2":"Certains ont une meilleure défense, ou une bonne vitesse, d'autres peuvent même utiliser de la magie pour attaquer ou soigner.",
    "dialogue4phrase1.1.2.1.1":"Exactement. La sentinelle qu'on a croisée à l'étage précédent est spécialisée en défense et ne se déplace que quand elle aperçoie un ennemi, alors que d'autres nous cherchent activement.",
    "dialogue4phrase1.1.2.1.2":"Ils souvent tous identiques au sein d'une espèce. Il est aussi plus rare de les voir en groupe. Parfois les humanoïdes les dressent pour le combat.",
    "dialogue4reponse1.1.1.1.2.1":"Et il faut qu'on combatte tout ça ? Ah, la galère...",
    "dialogue4reponse1.1.1.1.2.2":"Et bien, nous aussi, donc on s'en sortira !",
    "dialogue4reponse1.1.2.1.1.1":"Pourquoi faut-il qu'ils nous en veuillent tous...",
    "dialogue4reponse1.1.2.1.1.2":"Ces gobelins sont bien organisés.",
    "dialogue4phrase1.1.1.1.2.1":"Hélas...",
    "dialogue4phrase1.1.1.1.2.2":"Oui ! Je te fais confiance !",
    "dialogue4phrase1.1.2.1.1.1":"La plupart des monstres ont une dent contre les humains, mais pas tous. Il arrive même qu'ils se battent entre espèces.",
    "dialogue4phrase1.1.2.1.1.2":"C'est peut-être parce qu'ils ont un chef ? Les orcs sont un peu pareil.",
    "dialogue4reponse1.1.1.1.2.1.1":"Bon, allons-y.",
    "dialogue4reponse1.1.2.1.1.1.1":"Il y a beaucoup d'espèces de monstres dans ce labyrinthe ?",
    "dialogue4reponse1.1.2.1.1.2.1":"Je vois... Bon, allons-y.",
    "dialogue4phrase1.1.2.1.1.1.1":"Je ne sais pas, et j'espère en croiser le moins possible...",
    "dialogue4reponse1.1.2.1.1.1.1.1":"Ne t'inquiète pas, je te protégerai.",
    "dialogue4reponse1.1.2.1.1.1.1.2":"On verra bien. Allons-y.",
    "dialogue4phrase1.1.2.1.1.1.1.1":"Merci !",
    "dialogue5phrase1":"Est-ce que tu sais comment continuer ?",
    "dialogue5reponse1.1":"Euh... non ?",
    "dialogue5reponse1.2":"Oui, merci de demander.",
    "dialogue5reponse1.3":"Évidemment, je ne suis pas stupide !",
    "dialogue5phrase1.1":"Tu vas devoir passer par la porte.",
    "dialogue5reponse1.1.1":"Oh, je vois...",
    "dialogue5reponse1.1.2":"Cet espèce de mur orange ?",
    "dialogue5phrase1.1.1":"",
    "dialogue5phrase1.1.2":"C'est ça.",
    "dialogue5reponse1.1.1.1":"Mais elle est fermée.",
    "dialogue5phrase1.1.1.1":"Tu pourrais essayer avec cette clé ? Je l'ai trouvée tout à l'heure.",
    "dialogue5reponse1.1.1.1.1":"Merci. J'y vais alors.",
    "dialogue6phrase1":"Il y a deux portes maintenant.",
    "dialogue6reponse1.1":"Mais elles sont toutes les deux fermées !",
    "dialogue6reponse1.2":"Heureusement, je sais comment les ouvrir.",
    "dialogue6reponse1.3":"Je sais, je ne suis pas idiot...",
    "dialogue6phrase1.1":"Regarde, il y a une clé par terre.",
    "dialogue6reponse1.1.1":"Je vois ça ! Comment je la ramasse ?",
    "dialogue6phrase1.1.1":"En appuyant sur la touche M. Attention, s'il y a beaucoup d'objets sur une case, le ramassage risque de t'immobiliser pendant longtemps !",
    "dialogue6reponse1.1.1.1":"Ok, je ferais attention !",
    "dialogue7phrase1":"Tu as remarqué le portail de téléportation ?",
    "dialogue7reponse1.1":"Oui.",
    "dialogue7reponse1.2":"Cet espèce de mur bleu ?",
    "dialogue7reponse1.3":"Évidemment ! Maintenant laisse-moi chercher la sortie.",
    "dialogue7phrase1.1":"Celui-ci est un portail à double-sens, heureusement.",
    "dialogue7phrase1.2":"C'est ça.",
    "dialogue7reponse1.1.1":"J'espère que je ne tomberai pas dans un tel piège.",
    "dialogue7reponse1.1.2":"Il y en a qui ne passent que dans un sens ?",
    "dialogue7reponse1.1.3":"Bah, je n'ai qu'à tuer tout ce qu'il y a au-delà. Pourquoi revenir en arrière ?",
    "dialogue7reponse1.2.1":"",
    "dialogue7phrase1.1.1":"Ici, tu risques plutôt d'avoir des problèmes à cause du manque de place.",
    "dialogue7phrase1.1.2":"Il y en a aussi qui sont invisibles...",
    "dialogue7phrase1.1.3":"Si tu tombes dans un cul-de-sac, ça peut vite devenir compliqué... même sans portail à sens unique en fait, dans des petits espaces comme ici.",
    "dialogue7reponse1.1.1.1":"En quoi le manque de place est-il dérangeant ?",
    "dialogue7reponse1.1.1.2":"C'est vrai. D'ailleurs, il faut que j'aille donner quelques consignes. Je t'appellerais à nouveau à l'occasion.",
    "dialogue7reponse1.1.2.1":"Ugh. Pourquoi faut-il qu'il y ait de tels pièges...",
    "dialogue7reponse1.1.3.1":"Ha, vraiment ? On s'en moque, que ça soit petit ici.",
    "dialogue7reponse1.1.3.2":"Mais oui, bien sûr. J'ai plus important à faire, j'y vais.",
    "dialogue7phrase1.1.1.1":"Dans des espaces aussi petits, c'est facile d'être bloqué par d'autres. Si, par exemple, tu cherches à fuir un monstre et tu te retrouves bloqué face à quelqu'un qui va au corps-à-corps, tu peux en mourir.",
    "dialogue7phrase1.1.3.1":"Pas vraiment, non. Si, par exemple, tu cherches à fuir un monstre et tu te retrouves bloqué face à quelqu'un qui va au corps-à-corps, tu peux en mourir.",
    "dialogue7reponse1.1.1.1":"Je vois... C'est en effet plus difficile de se contourner.",
    "dialogue7phrase1.1.1.1":"Cependant, quelques consignes peuvent aider à organiser les déplacements.",
    "dialogue7reponse1.1.1.1.1":"Des consignes ? Comment je fais ça ?",
    "dialogue7reponse1.1.1.1.2":"Certes. Justement, je vais aller en donner avant de progresser plus loin.",
    "dialogue7phrase1.1.1.1.1":"Tu sais comment communiquer ?",
    "dialogue7reponse1.1.1.1.1.1":"Euh... non.",
    "dialogue7reponse1.1.1.1.1.2":"Oui, l'épéiste que j'ai rencontré juste après ma chute m'a expliqué.",
    "dialogue7phrase1.1.1.1.1.1":"Lorsque tu es à côté de quelqu'un, appuie sur la touche Espace pour dialoguer. Il ne faut pas que ton curseur de zone soit sur un élément séléctionable.",
    "dialogue7phrase1.1.1.1.1.2":"Après avoir commencé le dialogue, c'est tout simple. Tu dois choisir de quoi tu veux discuter, et ce que tu veux demander.",
    "dialogue7reponse1.1.1.1.1.1.1":"Oulà... Rappelle-moi cette histoire de zones ?",
    "dialogue7reponse1.1.1.1.1.1.2":"Ah, oui. Je m'en souviens maintenant.",
    "dialogue7reponse1.1.1.1.1.2.1":"Je peux demander tout ce que je veux ?",
    "dialogue7phrase1.1.1.1.1.1.1":"Tu dois avoir un curseur rouge quelque part sur ton écran. Tu peux le déplacer avec les touches A, E, Z, S, Q et D.",
    "dialogue7phrase1.1.1.1.1.2.1":"Presque. Mais pas sûr que tu sois exaucé...",
    "dialogue7reponse1.1.1.1.1.1.1.1":"J'ai beau appuyer, il ne se passe rien...",
    "dialogue7reponse1.1.1.1.1.2.1.1":"Ah... Zut.",
    "dialogue7phrase1.1.1.1.1.1.1.1":"Oui, les touches de zones ne fonctionnent pas pendant les dialogues.",
    "dialogue7phrase1.1.1.1.1.2.1.1":"Dans le cas des salles peu spacieuses, tu pourrais demander aux supports, comme moi, de rester à l'écart et à l'abri, puisqu'ils peuvent aider à distance. Ensuite, tu peux les rappeler de loin.",
    "dialogue7reponse1.1.1.1.1.1.1.1.1":"C'est donc pour ça.",
    "dialogue7reponse1.1.1.1.1.2.1.1.1":"Attends... les rappeler de loin ? Comment je fais ça ?",
    "dialogue7phrase1.1.1.1.1.1.1.1.1":"A et E permettent de changer de niveau, c'est-à-dire d'entrer dans les sous-menus et en sortir. Le menu le plus global est composé des trois zones d'affichages : le menu de gauche ; le carré central ; et l'affichage de droite. Tu peux passer de l'une à l'autre avec les touches Q et D, qui correspondent aux déplacements dans les listes horizontales.",
    "dialogue7phrase1.1.1.1.1.2.1.1.1":"Tu sais utiliser les touches de zones ?",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1":"Et je suppose que Z et S me déplacent dans les listes verticales... Et ensuite, une fois que j'ai sélectionné, par exemple, la zone de gauche ?",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.1":"Euh... un rappel ne fera pas de mal.",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.2":"Oui. Dans quelle zone est-ce que je dois aller ?",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1":"Tu peux utiliser la touche A pour entrer dans la zone de gauche, qui comprend trois sous-zones : en haut, tes informations avec tes points de vie et de mana ;  en dessous, ton iventaire ; et enfin ta classe, qui répertorie tes sous-classes et tes skills.",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.1":"Tu sais utiliser les touches de zones ?",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.2":"À gauche, dans la liste du haut qui répertorie tes alliés. Si tu appuies sur Espace, l'allié sélectionné viendra te voir de lui-même. Et si c'est toi qui est sélectionné, nous viendrons tous te voir. Enfin, à condition de savoir venir jusqu'à toi.",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1":"Pour rentrer dans l'inventaire par exemple, c'est encore A ?",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.1.1":"Tu dois avoir un curseur rouge quelque part sur ton écran. Tu peux le déplacer avec les touches A, E, Z, S, Q et D.",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.2.1":"Je vois... merci pour toutes ces explications !",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1.1":"Exactement. L'inventaire est lui-même organisé en catégories, qui contiennent les listes d'items. Une fois que tu as sélectionné un item, tu peux appuyer sur Espace pour l'utiliser, si c'est une potion, un parchemin ou un équippement. Puis tu peux ressortir de chaque niveau en appuyant sur E.",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.1.1":"J'ai beau appuyer, il ne se passe rien...",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1.1":"Donc si je veux utiliser un élément sélectionné avec les touches de zones, j'appuie sur Espace. Et quand je suis en dehors des zones, Espace me permet de dialoguer avec quelqu'un à côté de moi ?",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.1.1.1":"Oui, les touches de zones ne fonctionnent pas pendant les dialogues.",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1.1.1":"Pas que. Tu peux aussi interagir avec certains objets.",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.1.1.1":"C'est donc pour ça.",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1.1.1":"Hum... ça fait beaucoup pour une seule touche... mais revenons au dialogue.",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.1.1.1.1":"A et E permettent de changer de niveau, c'est-à-dire d'entrer dans les sous-menus et en sortir. Le menu le plus global est composé des trois zones d'affichages : le menu de gauche ; le carré central ; et l'affichage de droite. Tu peux passer de l'une à l'autre avec les touches Q et D, qui correspondent aux déplacements dans les listes horizontales.",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1.1.1.1":"Après avoir commencé le dialogue, c'est tout simple. Tu dois choisir de quoi tu veux discuter, et ce que tu veux demander.",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.1.1.1.1":"Et je suppose que Z et S me déplacent dans les listes verticales... Et ensuite, une fois que j'ai sélectionné, par exemple, la zone de gauche ?",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Je peux demander tout ce que je veux ?",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.1.1.1.1.1":"Tu peux utiliser la touche A pour entrer dans la zone de gauche, qui comprend trois sous-zones : en haut, tes informations avec tes points de vie et de mana ;  en dessous, ton iventaire ; et enfin ta classe, qui répertorie tes sous-classes et tes skills.",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Presque. Mais pas sûr que tu sois exaucé...",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.1.1.1.1.1":"Pour rentrer dans l'inventaire par exemple, c'est encore A ?",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Ah... Zut.",
    "dialogue7reponse1.1.1.1.1.2.1.1.1.1.1.1.1.1.1":"Exactement. L'inventaire est lui-même organisé en catégories, qui contiennent les listes d'items. Une fois que tu as sélectionné un item, tu peux appuyer sur Espace pour l'utiliser, si c'est une potion, un parchemin ou un équippement. Puis tu peux ressortir de chaque niveau en appuyant sur E.",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Dans le cas des salles peu spacieuses, tu pourrais demander aux supports, comme moi, de rester à l'écart et à l'abri, puisqu'ils peuvent aider à distance. Ensuite, tu peux les rappeler de loin.",
    "dialogue7phrase1.1.1.1.1.2.1.1.1.1.1.1.1.1.1":"Donc si je veux utiliser un élément sélectionné avec les touches de zones, j'appuie sur Espace. Et pour rappeler mes alliés de loin, dans quelle zone je dois aller ?",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Attends... les rappeler de loin ? Comment je fais ça ?",
    "dialogue7phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Avec les touches de zone !",
    "dialogue7reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Encore ? Et donc, dans quelle zone je dois aller ?",
    "dialogue-1phrase1":"Tu as besoin de quelque chose ?",
    "dialogue-1reponse1.1":"Tu pourrais aller quelque part ?",
    "dialogue-1reponse1.2":"Discutons un peu.",
    "dialogue-1reponse1.3":"Est-ce que tu pourrais placer une magie sur un parchemin ?",
    "dialogue-1reponse1.4":"Ce sera tout pour l'instant, merci.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1phrase1.3":"Bien sûr. Quelle magie veux-tu ?",
    "dialogue-1phrase1.3refus":"On dirait que tu n'as pas de parchemin vierge... Tu as besoin d'autre chose ?",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Ok. Tu as besoin d'autre chose ?",
    "dialogue-1phrase1.3.1":"Tu as besoin d'autre chose ?",
    "dialogue-1phrase1.3.1echec":"Je n'ai pas assez de mana pour cette magie... Tu as besoin d'autre chose ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.2":"C'est noté. Tu as besoin d'autre chose ?",
    "dialogue-2phrase1":"Tu as du culot de revenir me parler après ce que tu m'as dit !",
    "dialogue-2reponse1.1":""} #À compléter avec plus de répliques
