global REPLIQUES_PAUME
REPLIQUES_PAUME = {
    "dialogue1phrase1":"Quelle chance, il y a quelqu'un ici !",
    "dialogue1reponse1.1":"Bonjour.",
    "dialogue1reponse1.2":"Je ne fais que passer, au-revoir.",
    "dialogue1phrase1.1":"Où est-ce que tu vas comme ça ?",
    "dialogue1reponse1.1.1":"Je cherche la sortie.",
    "dialogue1phrase1.1.1":"Ces grottes sont un vrai labyrinthe, tu risquerais de te perdre !",
    "dialogue1reponse1.1.1.1":"Je vais y aller quand même.",
    "dialogue1reponse1.1.1.2":"Tu connais un autre chemin ?",
    "dialogue1phrase1.1.1.1":"Ton courage est impressionnant ! Moi, je suis ici depuis plusieurs jours.",
    "dialogue1phrase1.1.1.2":"Non...",
    "dialogue1reponse1.1.1.2.1":"Alors je n'ai pas d'autre choix que d'y aller",
    "dialogue1reponse1.1.1.1.1":"Tu peux venir avec moi, si ça te rassure.",
    "dialogue1reponse1.1.1.1.2":"Tu es vraiment pathétique.",
    "dialogue1phrase1.1.1.1.1":"Merci beaucoup ! N'hésite pas à me demander si tu as besoin de quelque-chose.",
    "dialogue1reponse1.1.1.1.1.1":"Je ferais appel à toi.",
    "dialogue1phrase1.1.1.1.1.1":"Au fait, tu peux courir avec R, mais évite de me perdre de vue s'il te plaît !",
    "dialogue1reponse1.1.1.1.1.1.1":"Merci du conseil",
    "dialogue2phrase1":"Le gobelin est mort !",
    "dialogue2reponse1.1":"Oui ! Mais il nous a blessés...",
    "dialogue2reponse1.2":"Pff, trop facile !",
    "dialogue2reponse1.3":"Je n'ai pas tout compris...",
    "dialogue2phrase1.1":"Ne t'inquiète pas, nos blessures se soignent avec le temps.",
    "dialogue2reponse1.1.1":"Ah, tu me rassures. En route alors !",
    "dialogue2reponse1.1.2":"Ouf ! Mais, je ne suis pas sûr d'avoir compris tout ce qui s'est passé.",
    "dialogue2phrase1.3":"Qu'est-ce que tu n'as pas compris ?",
    "dialogue2reponse1.3.1":"Comment est-ce que le gobelin est mort ?",
    "dialogue2reponse1.3.2":"C'était quoi, tous les trucs qu'on voyait ?",
    "dialogue2reponse1.3.3":"Pourquoi est-ce qu'il reste quelque chose ?",
    "dialogue2phrase1.3.1":"Il avait une barre rouge au-dessus de la tête, comme toi et moi. Cette barre représente ses PVs, et chacune de nos attaques lui a fait perdre des PVs. Quand ses PVs ont atteint 0, il est mort.",
    "dialogue2phrase1.3.2":"Les marques marrons représentaient les attaques. Il y avait aussi des points rouges à chaque fois que quelqu'un se faisait blesser.",
    "dialogue2phrase1.3.2/peureuse":"Les marques marrons représentaient les attaques. Il y avait aussi des points rouges à chaque fois que quelqu'un se faisait blesser. Et s'il y avait des espèces de cercles oranges sous nos pieds, c'étaient les magies de boost lancés par notre coéquipière. Tu as peut-être pu voir qu'elle-même avait un cercle bleu à chaque fois qu'elle lançait une magie.",
    "dialogue2phrase1.3.3":"Le corps du gobelin n'allait pas disparaître ! Son cadavre est toujours là. Il y a aussi les items qu'il transportait, en l'occurence son équippement.",
    "dialogue2reponse1.3.1.1":"Merci, c'est tout ce que je voulais savoir !",
    "dialogue2reponse1.3.1.2":"Il y a autre chose que je n'ai pas compris.",
    "dialogue3phrase1":"Il était coriace, celui-là !",
    "dialogue3reponse1.1":"C'est peu de le dire ! Qu'est-ce que c'était que ces attaques à distance !?",
    "dialogue3reponse1.2":"Mais non, c'était facile !",
    "dialogue3phrase1.1":"Aucune idée. Peut-être de la magie ?",
    "dialogue3reponse1.1.1":"J'aimerais pouvoir faire de la magie moi aussi...",
    "dialogue3reponse1.1.2":"Une tactique de faible !",
    "dialogue3phrase1.1.1":"Ça semble puissant comme ça, mais les mages sont toujours en train de manquer de mana...",
    "dialogue3phrase1.1.2":"En tous cas, ce n'était pas suffisant pour nous vaincre.",
    "dialogue3reponse1.1.1.1":"Et nous de PVs, chacun ses problèmes. Bon, on y retourne ?",
    "dialogue3reponse1.1.2.1":"Bien dit ! C'est pas tout ça, retournons explorer.",
    "dialogue4phrase1":"Est-ce que tu vois ces portes dans les murs autour de toi ?",
    "dialogue4reponse1.1":"Oui.",
    "dialogue4reponse1.2":"Ces barres oranges ?",
    "dialogue4reponse1.3":"Évidemment, je ne suis pas aveugle !",
    "dialogue4phrase1.1":"Il te faut des clés pour les ouvrir.",
    "dialogue4phrase1.2":"C'est ça. Il te faut des clés pour les ouvrir.",
    "dialogue4reponse1.1.1":"Des clés ? Où est-ce que je peux les trouver ?",
    "dialogue4phrase1.1.1":"Par terre, après avoir tué un monstre par exemple. Ramasse-les avec la touche M.",
    "dialogue4reponse1.1.1.1":"Ok, je regarderai autour de moi.",
    "dialogue-1phrase1":"Je peux me rendre utile ?",
    "dialogue-1reponse1.1":"Va quelque part.",
    "dialogue-1reponse1.2":"J'aimerais parler avec toi.",
    "dialogue-1reponse1.3":"C'est bon, merci.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Désolé, je... je n'ai vraiment pas le courage d'y aller tout seul. Je peux me rendre utile autrement ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.1":"Ok. Je peux faire autre chose ?",
    "dialogue-1phrase1.1.1.2":"C'est noté. Je peux faire autre chose ?",
    "dialogue-2phrase1":"Quoi ?",
    "dialogue-2reponse1.1":"Rien !",
    "dialogue-2reponse1.2":"Tu veux que je t'aide à sortir d'ici ?",
    "dialogue-2reponse1.3":"Je voudrais m'excuser pour ce que j'ai dit.",
    "dialogue-2phrase1.2":"Non merci, je préfère rester bloqué que demander ton aide !",
    "dialogue-2phrase1.3":"... Bon, je te pardonne.",
    "dialogue-2reponse1.2.1":"Eh bien reste-ici !",
    "dialogue-2reponse1.3.1":"Du coup, on va à la sortie ?",
    "dialogue-2phrase1.3.1":"Ok, montre-moi le chemin.",
    "dialogue-2reponse1.3.1.1":"Tache de ne pas te perdre.",
    "dialogue-2reponse1.3.1.2":"Fais-moi confiance !"} #À compléter avec plus de répliques
