# global REPLIQUES_BOMBE_ATOMIQUE
REPLIQUES_BOMBE_ATOMIQUE = {
    "dialogue1phrase1":"Bonjour mon chou...",
    "dialogue1reponse1.1":"Bonjour ma belle.",
    "dialogue1reponse1.2":"Euh... bonjour...",
    "dialogue1phrase1.1":"Qu'est-ce qui t'amène ici ?",
    "dialogue1phrase1.2":"",
    "dialogue1reponse1.1.1":"Je cherche la sortie.",
    "dialogue1reponse1.1.2":"Je t'ai aperçue de loin, et j'ai voulu faire ta connaissance.",
    "dialogue1reponse1.2.1":"...tu sais où est la sortie ?",
    "dialogue1reponse1.2.2":"...tu sais te battre ?",
    "dialogue1phrase1.1.1":"Moi aussi. On peut faire un bout de chemin ensemble ?",
    "dialogue1phrase1.1.2":"Ahah... Tu veux que je tienne un peu compagnie ?",
    "dialogue1phrase1.2.1":"Au centième étage. Tu as encore du chemin à faire...",
    "dialogue1phrase1.2.2":"Tu veux que je te montre ?",
    "dialogue1reponse1.1.1.1":"Avec plaisir.",
    "dialogue1reponse1.1.1.2":"Non merci.",
    "dialogue1reponse1.1.2.1":"Comment refuser une compagnie si agréable ?",
    "dialogue1reponse1.2.1.1":"Tu pourrais m'aider ?",
    "dialogue1reponse1.2.1.2":"Je n'ai pas de temps à perdre alors. À plus.",
    "dialogue1reponse1.2.2.1":"Non, je te crois. Ça t'intéresserait de venir avec moi ?",
    "dialogue1reponse1.2.2.2":"Ouais, amène-toi.",
    "dialogue1phrase1.2.1.1":"Je suppose que je peux faire un bout de chemin avec toi.",
    "dialogue1phrase1.2.2.1":"Oui. Demande-moi si tu as un monstre à carboniser.",
    "dialogue1phrase1.2.2.2":"Non, je voulais dire, te montrer sur les monstres.",
    "dialogue1reponse1.2.1.1.1":"Merci.",
    "dialogue1reponse1.2.2.1.1":"J'y penserai.",
    "dialogue1reponse1.2.2.2.1":"Pff. Je te fais peur ?",
    "dialogue1reponse1.2.2.2.2":"Ok. Accompagne-moi alors.",
    "dialogue1phrase1.2.2.2.1":"Tu l'aura voulu...",
    "dialogue1reponse1.2.2.2.1.1":"",
    "dialogue-1phrase1":"Tu as besoin d'aide, mon chou ?",
    "dialogue-1reponse1.1":"Est-ce que tu peux aller quelque part ?",
    "dialogue-1reponse1.2":"On peut parler en privé ?",
    "dialogue-1reponse1.3":"Est-ce que tu peux placer une magie sur un parchemin ?",
    "dialogue-1reponse1.4":"C'est tout, merci !",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"En privé ? Dans ce labyrinthe rempli à craquer de monstres et d'humains ? Ça risque d'être compliqué...",
    "dialogue-1phrase1.3":"Bien sûr. Quelle magie veux-tu ?",
    "dialogue-1phrase1.3refus":"On dirait que tu n'as pas de parchemin vierge... Je peux faire autre chose ?",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Ok. Je peux faire autre chose ?",
    "dialogue-1phrase1.3.1":"Je peux faire autre chose ?",
    "dialogue-1phrase1.3.1echec":"Je n'ai pas assez de mana pour cette magie... Je peux faire autre chose ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.2":"C'est noté. Je peux faire autre chose ?",
    "dialogue-2phrase1":"Ah, c'est encore toi ?",
    "dialogue-2reponse1.1":"Tu ne voudrais pas m'accompagner ?",
    "dialogue-2reponse1.2":"Désolé, je me suis trompé de personne.",
    "dialogue-2phrase1.1":"Ok.",
    "dialogue-2reponse1.1.1":"",
    "dialogue-3phrase1":"Alors, qu'est-ce que tu penses de ma magie ?",
    "dialogue-3reponse1.1":"Tu m'as convaincu. Tu pourrais arrêter de m'attaquer maintenant ?",
    "dialogue-3phrase1.1":"Comment ? Je n'entends rien avec toutes ces explosions.",
    "dialogue-3reponse1.1.1":"..."} #À compléter avec plus de répliques
