global REPLIQUES_ALCHIMISTE
REPLIQUES_ALCHIMISTE = {
    "dialogue1phrase1":"Ho ho ho ! Y aurait-il d'autres humains coincés ici ?",
    "dialogue1reponse1.1":"Oui, tu veux nous rejoindre ?",
    "dialogue1reponse1.2":"Ne fais pas attention, vieillard, on ne faisait que passer.",
    "dialogue1phrase1.1":"Avec grand plaisir ! Mes talents d'alchimiste vous serons d'une grande aide.",
    "dialogue1reponse1.1.1":"Un alchimiste ! Qu'est-ce que tu peux faire ?",
    "dialogue1reponse1.1.2":"Je ferais appel à toi.",
    "dialogue1phrase1.1.1":"Créer et examiner des potions et des parchemins, principalement... Je sais aussi utiliser plein de magies.",
    "dialogue2phrase1":"Tu as vu ça ? C'était un téléporteur !",
    "dialogue2reponse1.1":"Oui, j'ai remarqué...",
    "dialogue2reponse1.2":"Cet espèce de mur bleu ?",
    "dialogue2reponse1.3":"Je sais, je sais.",
    "dialogue-1phrase1":"Mes talents sont-ils requis ?",
    "dialogue-1reponse1.1":"J'ai besoin que tu ailles quelque part.",
    "dialogue-1reponse1.2":"On peut discuter ?",
    "dialogue-1reponse1.3":"Est-ce que tu pourrais placer une magie sur un parchemin ?",
    "dialogue-1reponse1.4":"Tu peux me faire un item ?",
    "dialogue-1reponse1.5":"Non merci, c'est suffisant.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1phrase1.3":"Bien sûr. Quelle magie veux-tu ?",
    "dialogue-1phrase1.3refus":"On dirait que tu n'as pas de parchemin vierge... Je peux faire autre chose ?",
    "dialogue-1phrase1.4":"Bien sûr, quoi ?",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1reponse1.4.1":"Parchemin vierge",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Ok. Je peux faire autre chose ?",
    "dialogue-1phrase1.3.1":"Je peux faire autre chose ?",
    "dialogue-1phrase1.3.1echec":"Je n'ai pas assez de mana pour cette magie... Je peux faire autre chose ?",
    "dialogue-1phrase1.4.1":"Voilà. Tu veux que j'y impregne une magie ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1reponse1.4.1.1":"Oui, s'il te plait.",
    "dialogue-1reponse1.4.1.2":"Non merci.",
    "dialogue-1phrase1.1.1.2":"C'est noté. Tu as besoin d'autre chose ?",
    "dialogue-2phrase1":"Qu'est-ce qu'il y a, le mioche ?",
    "dialogue-2reponse1.1":"Tu ne voudrais pas rejoindre notre groupe ? Pour ta propre sécurité.",
    "dialogue-2reponse1.2":"Désolé pour mon comportement.",
    "dialogue-2phrase1.1":"Non merci, je me débrouille très bien tout seul.",
    "dialogue-2phrase1.2":"Je vais laisser passer pour cette fois.",
    "dialogue-2reponse1.1.1":"Comme tu voudras.",
    "dialogue-2reponse1.1.2":"Ne t'étonne pas de mourir !",
    "dialogue-2reponse1.2.1":"Du coup, est-ce que tu voudrais rejoindre notre groupe ?",
    "dialogue-2phrase1.2.1":"Pourquoi pas. On est plus forts à plusieurs.",
    "dialogue-2reponse1.2.1":"Bienvenu. Et encore désolé."} #À compléter avec plus de répliques
