global REPLIQUES_ENCOMBRANT
REPLIQUES_ENCOMBRANT = {
    "dialogue1phrase1":"Hey, salut ! Moi c'est [insérer le nom du copain ici].",
    "dialogue1reponse1.1":"Moi c'est Arvel.",
    "dialogue1reponse1.2":"Alors c'est toi, son copain !",
    "dialogue1phrase1.1":"Content de te voir !",
    "dialogue1phrase1.2":"Quoi ?",
    "dialogue1reponse1.1.1":"Moi aussi ! Tu veux rejoindre mon groupe ?",
    "dialogue1reponse1.1.2":"Ouais, ouais...",
    "dialogue1reponse1.2.1":"Non, rien. Ta copine m'a parlé de toi.",
    "dialogue1reponse1.2.2":"Je vais te tuer, mais ce n'est rien de personnel.",
    "dialogue1phrase1.1.1":"Volontiers ! Tiens, j'ai trouvé cette clé tout à l'heure.",
    "dialogue1phrase1.1.2":"Comment ça, 'Ouais, ouais...' ?",
    "dialogue1phrase1.2.1":"J'ai hâte de la revoir !",
    "dialogue1reponse1.1.1.1":"Cool ! On y va alors !",
    "dialogue1reponse1.1.2.1":"Tu es un peu trop exhubérant pour moi. Je vais te laisser ici.",
    "dialogue1reponse1.2.1.1":"Je suppose que tu voudras rejoindre mon groupe alors ?",
    "dialogue1phrase1.1.1.1":"Merci pour ça. Je te le revaudrai.",
    "dialogue1reponse1.1.1.1.1":"Alors je te demanderai si j'ai besoin d'aide.",
    "dialogue-1phrase1":"Tu as besoin de quelque chose ?",
    "dialogue-1reponse1.1":"Tu pourrais aller quelque part ?",
    "dialogue-1reponse1.2":"Discutons un peu.",
    "dialogue-1reponse1.3":"Non, merci, c'est tout.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Ok. Tu as besoin d'autre chose ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.2":"C'est noté. Tu as besoin d'autre chose ?",
    "dialogue-2phrase1":"Meurs !",
    "dialogue-2reponse1.1":""} #À compléter avec plus de répliques
