# global REPLIQUES_PESTE
REPLIQUES_PESTE = {
    "dialogue1phrase1":"Hey, toi !",
    "dialogue1reponse1.1":"Qu'est-ce qu'il y a ?",
    "dialogue1reponse1.2":"Ne me parle pas comme ça !",
    "dialogue1phrase1.1":"J'ai besoin d'aide pour tuer tous ces immondes monstres.",
    "dialogue1phrase1.2":"Quoi !?",
    "dialogue1reponse1.1.1":"Tu pourrais rejoindre notre groupe.",
    "dialogue1reponse1.1.2":"Est-on obligés de tous les tuer ?",
    "dialogue1reponse1.2.1":"Ta façon de m'interpeler n'était pas très polie...",
    "dialogue1reponse1.2.2":"Tu te crois supérieure, peut-être ? Figure-toi que je suis l'un des douze élus !",
    "dialogue1phrase1.1.1":"Ok. Je peux vous soigner si ces sales monstres vous blessent.",
    "dialogue1phrase1.1.2":"Tu voudrais laisser ces vermines en vie !?",
    "dialogue1phrase1.2.1":"Ouais, ouais, désolé. Qu'est-ce que tu fais ici de toute façon ?",
    "dialogue1phrase1.2.2":"L'un des douzes ? Toi ? Je préfère m'en aller que d'écouter ces bêtises.",
    "dialogue1reponse1.1.1.1":"Tu as des capacité de guérison ?",
    "dialogue1reponse1.1.1.2":"D'accord.",
    "dialogue1reponse1.1.2.1":"Non, non, bien sûr que non...",
    "dialogue1reponse1.1.2.2":"Si ça peut nous éviter des mort inutiles...",
    "dialogue1reponse1.2.1.1":"Je me demandais si tu voulais peut-être rejoindre notre groupe...",
    "dialogue1reponse1.2.2.1":"C'est ça, bon débarras !",
    "dialogue1phrase1.1.1.1":"Je suis la Sainte choisie par le grand Dieu [insérer le nom d'un Dieu ici] ! Tu ne trouveras pas de meilleure guérisseuse dans tout [insérer le nom d'une capitale ici].",
    "dialogue1phrase1.1.2.1":"Alors, tu m'aides ?",
    "dialogue1phrase1.2.1.1":"",
    "dialogue1reponse1.1.1.1.1":"Waoh ! Je compterais sur toi alors.",
    "dialogue1reponse1.1.2.1.1":"Non, je me débrouillerai tout seul.",
    "dialogue1reponse1.1.2.1.2":"Je veux bien.",
    "dialogue1reponse1.2.1.1.1":"...ça t'intéresse ?",
    "dialogue1reponse1.2.1.1.1":"...mais après réflexion, je ne te veux pas dans mon groupe.",
    "dialogue1phrase1.2.1.1.1":"Ouais. Ça sera plus efficace que de combattre dans mon coin...",
    "dialogue1reponse1.2.1.1.1.1":"Merci. Je compterais sur toi.",
    "dialogue-1phrase1":"Qu'est-ce qu'il y a ?",
    "dialogue-1reponse1.1":"Si tu vas à un certain endroit, on pourrait tuer plus de monstres.",
    "dialogue-1reponse1.2":"Je voulais te parler d'un truc.",
    "dialogue-1reponse1.3":"Est-ce que tu pourrais placer une magie sur un parchemin ?",
    "dialogue-1reponse1.4":"Non, c'est tout.",
    "dialogue-1phrase1.1":"Vraiment ? Où ça ?",
    "dialogue-1phrase1.2":"Tu crois que j'ai envie de discuter avec toi ?",
    "dialogue-1phrase1.2elu":"Désolé, je n'ai pas le temps. On ferait mieux de tuer des monstres !",
    "dialogue-1phrase1.3":"Quelle magie veux-tu ?",
    "dialogue-1phrase1.3refus":"On dirait que tu n'as pas de parchemin vierge... Autre chose ?",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"...",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1phrase1.1.1":"Je ferais n'importe quoi si ça peut aider à exterminer ces monstres. Qui est-ce que je dois suivre ?",
    "dialogue-1phrase1.1.3":"Tout de suite ! Autre chose ?",
    "dialogue-1phrase1.3.1":"Autre chose ?",
    "dialogue-1phrase1.3.1echec":"Je n'ai pas assez de mana pour cette magie... Autre chose ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.1":"D'accord. Autre chose ?",
    "dialogue-1phrase1.1.1.2":"C'est noté. Autre chose ?",
    "dialogue-2phrase1":"(Je n'arriverai jamais à tuer tous les monstres toute seule...)",
    "dialogue-2reponse1.1":"Tu parles toute seule ? Tu ne serais pas un peu folle ?",
    "dialogue-2reponse1.2":"On peut s'entraider pour tuer les monstres ?",
    "dialogue-2phrase1.1":"Comment oses-tu m'insulter !? Subit le châtiment divin !",
    "dialogue-2phrase1.2":"Tu as besoin de moi finalement ?",
    "dialogue-2reponse1.1.1":"...",
    "dialogue-2reponse1.2.1":"Je suppose que oui.",
    "dialogue-3phrase1":"Tu peux me laisser ? J'ai des monstres à  tuer.",
    "dialogue-3reponse1.1":"...",
    "dialogue-4phrase1":"Subit le châtiment divin !",
    "dialogue-4reponse1.1":"..."} #À compléter avec plus de répliques
