# global REPLIQUES_MARCHAND
REPLIQUES_MARCHAND = {
    "dialogue1phrase1":"Vous avez besoin de quelque chose ?",
    "dialogue1reponse1.1":"Vous pouvez faire quelque chose pour moi ?",
    "dialogue1phrase1.1":"Bien sûr ! Je suis marchand, et je peux vous proposer toutes sortes d'objets. Certains articles coûtent un peu cher, mais vu les circonstances, vous ne trouverez pas mieux !",
    "dialogue1reponse1.1.1":"Intéressant... tu veux venir avec moi ?",
    "dialogue1reponse1.1.2":"Je n'ai pas d'argent...",
    "dialogue1phrase1.1.1":"Volontiers. Il n'y a pas beaucoup d'autres clients ici.",
    "dialogue1phrase1.1.2":"Tu n'as qu'à me vendre ce dont tu ne te sers pas. Même les cadavres de monstres ont de la valeur.",
    "dialogue1reponse1.1.1.1":"",
    "dialogue1reponse1.1.2.1":"Ce serait embêtant de revenir ici à chaque fois que j'ai tué un monstre...",
    "dialogue1phrase1.1.2.1":"Je peux t'accompagner.",
    "dialogue1reponse1.1.2.1.1":"Je veux bien.",
    "dialogue1reponse1.1.2.1.2":"Non merci.",
    "dialogue-1phrase1":"Un client !",
    "dialogue-1reponse1.1":"Non, je voulais te donner une consigne.",
    "dialogue-1reponse1.2":"Je voudrais vendre.",
    "dialogue-1reponse1.3":"Je voudrais acheter.",
    "dialogue-1phrase1.1":"Bien sûr, quoi ?",
    "dialogue-1phrase1.2":"Désolé, j'ai du mal à utiliser mon skill en ce moment.",
    "dialogue-1reponse1.1.1":"Tu pourrais aller quelque part ?",
    "dialogue-1reponse1.1.2":"Discutons un peu.",
    "dialogue-1reponse1.1.3":"Merci, c'est tout.",
    "dialogue-1reponse1.2.1":"...",
    "dialogue-1phrase1.1.1":"Où ?",
    "dialogue-1phrase1.1.2":"On a pas vraiment le temps, là...",
    "dialogue-1reponse1.1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1phrase1.1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.1.2":"Ok. Tu as besoin d'autre chose ?",
    "dialogue-1reponse1.1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.1.1":"Ok. Tu as besoin d'autre chose ?",
    "dialogue-1phrase1.1.1.1.2":"C'est noté. Tu as besoin d'autre chose ?",
    "dialogue-2phrase1":"Un client !",
    "dialogue-2reponse1.1":"Je voudrais vendre.",
    "dialogue-2reponse1.2":"Je voudrais acheter.",
    "dialogue-2phrase1.1":"Désolé, j'ai du mal à utiliser mon skill en ce moment.",
    "dialogue-2reponse1.1.1":"..."} #À compléter avec plus de répliques
