global REPLIQUES_CODEUR
REPLIQUES_CODEUR = {
    "dialogue-1phrase1":"Salut, qu'est-ce que tu viens faire ici ?",
    "dialogue-1reponse1.1":"Je me suis perdu !",
    "dialogue-1reponse1.2":"Je voulais explorer tous les recoins.",
    "dialogue-1phrase1.1":"C'est un labyrinthe, c'est fait pour ça...",
    "dialogue-1phrase1.2":"Tu as bien raison. Observe, examine, scrute les moindres détails, cherche la vérité, et tu seras victorieux !",
    "dialogue-1reponse1.1.1":"",
    "dialogue-1reponse1.2.1":"Ça va vraiment m'aider à combattre les monstres ?",
    "dialogue-1reponse1.2.2":"Quels genre de détails dois-je chercher ?",
    "dialogue-1phrase1.2.1":"Pas vraiment.",
    "dialogue-1phrase1.2.2":"Tu peux observer les inscriptions sur les murs, écouter ce que les PNJs ont à te dire... la suite viendra plus tard.",
    "dialogue-1reponse1.2.1.1":"Je vais y aller alors.",
    "dialogue-1reponse1.2.2.1":"Merci pour ces conseils.",
    "dialogue-2phrase1":"Salut, qu'est-ce que tu viens faire ici ?",
    "dialogue-2reponse1.1":"Je me suis perdu !",
    "dialogue-2reponse1.2":"Je voulais explorer tous les recoins.",
    "dialogue-2phrase1.1":"C'est un labyrinthe, c'est fait pour ça...",
    "dialogue-2phrase1.2":"Vraiment ? Tu viens de me dire que tu t'étais perdu pourtant...",
    "dialogue-2reponse1.1.1":"",
    "dialogue-2reponse1.2.1":"",
    "dialogue-2phrase1.2.1":"Tu pensais vraiment que je ne m'en souviendrais pas ?",
    "dialogue-2reponse1.2.1.1":"Désolé, je ne voulais pas te mentir...",
    "dialogue-2phrase1.2.1.1":"Allez, vas-y.",
    "dialogue-2reponse1.2.1.1.1":"",
    "dialogue-3phrase1":"Alors, comment vont tes combats ?",
    "dialogue-3reponse1.1":"Bien, merci.",
    "dialogue-4phrase1":"Tu n'obtiendras rien de plus de moi.",
    "dialogue-4reponse1.1":"",
    "dialogue-5phrase1":"Salut, quoi de neuf ?",
    "dialogue-5reponse1.1":"Est-ce que je peux entendre tes conseils à nouveaux ?",
    "dialogue-5reponse1.2":"Je passais juste dire bonjour.",
    "dialogue-5phrase1.1":"Quelle partie ? 'Observe, examine, scrute les moindres détails, cherche la vérité, et tu seras victorieux !' ou 'Tu peux observer les inscriptions sur les murs, écouter ce que les PNJs ont à te dire... la suite viendra plus tard.' ?",
    "dialogue-5phrase1.2":"Tu as des choses plus importantes à faire...",
    "dialogue-5reponse1.1.1":"Les deux, merci !",
    "dialogue-5reponse1.2.1":"Oui, j'y vais"} #À compléter avec plus de répliques
