REPLIQUES_ALCHIMISTE = {
    "dialogue1phrase1":"Ho ho ho ! Y aurait-il d'autres humains coincés ici ?",
    "dialogue1reponse1.1":"Oui, tu veux nous rejoindre ?",
    "dialogue1reponse1.2":"Ne fais pas attention, vieillard, on ne faisait que passer.",
    "dialogue1phrase1.1":"Avec grand plaisir ! Mes talents d'alchimiste vous serons d'une grande aide.",
    "dialogue1reponse1.1.1":"Un alchimiste ! Qu'est-ce que tu peux faire ?",
    "dialogue1reponse1.1.2":"Je ferais appel à toi.",
    "dialogue1phrase1.1.1":"Créer et examiner des potions et des parchemins, principalement... Je sais aussi utiliser plein de magies.",
    "dialogue2phrase1":"Tu as vu ça ? C'était un portail de téléportation !",
    "dialogue2reponse1.1":"Oui, j'ai remarqué.",
    "dialogue2reponse1.2":"Cet espèce de mur bleu ?",
    "dialogue2reponse1.3":"Si tu as le temps de me faire perdre le mien à parler de téléporteurs, va combattre les gobelins !",
    "dialogue2phrase1.1":"Et repasser dans l'autre sens ramène au point de départ ! J'espère que je pourrai apprendre cette magie un jour.",
    "dialogue2phrase1.2":"Oui. Le traverser t'a envoyé à un autre endroit !",
    "dialogue2reponse1.1.1":"J'espère pour toi !",
    "dialogue2reponse1.1.2":"Ces portails ont été créés par une magie ? Ils vont finir par disparaître ?",
    "dialogue2reponse1.1.3":"Pff ! À quoi ça te servirait, de toute façon ?",
    "dialogue2reponse1.2.1":"...",
    "dialogue2phrase1.1.1":"En plus, les magies spaciales sont très utiles, surtout dans des petits espaces comme ici.",
    "dialogue2phrase1.1.2":"Je ne sais pas comment ceux-ci ont été faits, mais la magie que je veux apprendre crée des portails permanents.",
    "dialogue2phrase1.1.3":"Moque-toi si tu veux, mais les magies spaciales sont très utiles, surtout dans des petits espaces comme ici.",
    "dialogue2reponse1.1.1.1":"En quoi la taille de cet endroit est-elle dérangeante ?",
    "dialogue2reponse1.1.1.2":"C'est vrai. D'ailleurs, il faut que j'aille donner quelques consignes. Je t'appellerais à nouveau à l'occasion.",
    "dialogue2reponse1.1.2.1":"C'est impressionnant ! J'espère que tu pourras l'apprendre.",
    "dialogue2reponse1.1.3.1":"Ha, vraiment ? On s'en moque, que ça soit petit ici.",
    "dialogue2reponse1.1.3.2":"Mais oui, bien sûr. J'ai plus important à faire, j'y vais.",
    "dialogue2phrase1.1.1.1":"Dans des espaces aussi petits, c'est facile d'être bloqué par d'autres. Si, par exemple, tu cherches à fuir un monstre et tu te retrouves bloqué face à quelqu'un qui va au corps-à-corps, tu peux en mourir.",
    "dialogue2phrase1.1.3.1":"Pas vraiment, non. Si, par exemple, tu cherches à fuir un monstre et tu te retrouves bloqué face à quelqu'un qui va au corps-à-corps, tu peux en mourir.",
    "dialogue2reponse1.1.1.1":"Je vois... C'est en effet plus difficile de se contourner.",
    "dialogue2phrase1.1.1.1":"À défaut de magie spatiale, quelques consignes peuvent aider à organiser les déplacements.",
    "dialogue2reponse1.1.1.1.1":"Des consignes ? Comment je fais ça ?",
    "dialogue2reponse1.1.1.1.2":"Certes. Justement, je vais aller en donner avant de progresser plus loin.",
    "dialogue2phrase1.1.1.1.1":"Tu sais comment communiquer ?",
    "dialogue2reponse1.1.1.1.1.1":"Euh... non.",
    "dialogue2reponse1.1.1.1.1.2":"Oui, l'épéiste que j'ai rencontré juste après ma chute m'a expliqué.",
    "dialogue2phrase1.1.1.1.1.1":"Lorsque tu es à côté de quelqu'un, appuie sur la touche Espace pour dialoguer. Il ne faut pas que ton curseur de zone soit sur un élément séléctionable.",
    "dialogue2phrase1.1.1.1.1.2":"Après avoir commencé le dialogue, c'est tout simple. Tu dois choisir de quoi tu veux discuter, et ce que tu veux demander.",
    "dialogue2reponse1.1.1.1.1.1.1":"Oulà... Rappelle-moi cette histoire de zones ?",
    "dialogue2reponse1.1.1.1.1.1.2":"Ah, oui. Je m'en souviens maintenant.",
    "dialogue2reponse1.1.1.1.1.2.1":"Je peux demander tout ce que je veux ?",
    "dialogue2phrase1.1.1.1.1.1.1":"Tu dois avoir un curseur rouge quelque part sur ton écran. Tu peux le déplacer avec les touches A, E, Z, S, Q et D.",
    "dialogue2phrase1.1.1.1.1.2.1":"Presque. Mais pas sûr que tu sois exaucé...",
    "dialogue2reponse1.1.1.1.1.1.1.1":"J'ai beau appuyer, il ne se passe rien...",
    "dialogue2reponse1.1.1.1.1.2.1.1":"Ah... Zut.",
    "dialogue2phrase1.1.1.1.1.1.1.1":"Oui, les touches de zones ne fonctionnent pas pendant les dialogues.",
    "dialogue2phrase1.1.1.1.1.2.1.1":"Dans le cas des salles peu spacieuses, tu pourrais demander aux supports de rester à l'écart et à l'abri, puisqu'ils peuvent aider à distance. Ensuite, tu peux les rappeler de loin.",
    "dialogue2reponse1.1.1.1.1.1.1.1.1":"C'est donc pour ça.",
    "dialogue2reponse1.1.1.1.1.2.1.1.1":"Attends... les rappeler de loin ? Comment je fais ça ?",
    "dialogue2phrase1.1.1.1.1.1.1.1.1":"A et E permettent de changer de niveau, c'est-à-dire d'entrer dans les sous-menus et en sortir. Le menu le plus global est composé des trois zones d'affichages : le menu de gauche ; le carré central ; et l'affichage de droite. Tu peux passer de l'une à l'autre avec les touches Q et D, qui correspondent aux déplacements dans les listes horizontales.",
    "dialogue2phrase1.1.1.1.1.2.1.1.1":"Tu sais utiliser les touches de zones ?",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1":"Et je suppose que Z et S me déplacent dans les listes verticales... Et ensuite, une fois que j'ai sélectionné, par exemple, la zone de gauche ?",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.1":"Euh... un rappel ne fera pas de mal.",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.2":"Oui. Dans quelle zone est-ce que je dois aller ?",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1":"Tu peux utiliser la touche A pour entrer dans la zone de gauche, qui comprend trois sous-zones : en haut, tes informations avec tes points de vie et de mana ;  en dessous, ton iventaire ; et enfin ta classe, qui répertorie tes sous-classes et tes skills.",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.1":"Tu sais utiliser les touches de zones ?",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.2":"À gauche, dans la liste du haut qui répertorie tes alliés. Si tu appuies sur Espace, l'allié sélectionné viendra te voir de lui-même. Et si c'est toi qui est sélectionné, nous viendrons tous te voir. Enfin, à condition de savoir venir jusqu'à toi.",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1":"Pour rentrer dans l'inventaire par exemple, c'est encore A ?",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.1.1":"Tu dois avoir un curseur rouge quelque part sur ton écran. Tu peux le déplacer avec les touches A, E, Z, S, Q et D.",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.2.1":"Je vois... merci pour toutes ces explications !",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1.1":"Exactement. L'inventaire est lui-même organisé en catégories, qui contiennent les listes d'items. Une fois que tu as sélectionné un item, tu peux appuyer sur Espace pour l'utiliser, si c'est une potion, un parchemin ou un équippement. Puis tu peux ressortir de chaque niveau en appuyant sur E.",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.1.1":"J'ai beau appuyer, il ne se passe rien...",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1.1":"Donc si je veux utiliser un élément sélectionné avec les touches de zones, j'appuie sur Espace. Et quand je suis en dehors des zones, Espace me permet de dialoguer avec quelqu'un à côté de moi ?",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.1.1.1":"Oui, les touches de zones ne fonctionnent pas pendant les dialogues.",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1.1.1":"Pas que. Tu peux aussi interagir avec certains objets.",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.1.1.1":"C'est donc pour ça.",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1.1.1":"Hum... ça fait beaucoup pour une seule touche... mais revenons au dialogue.",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.1.1.1.1":"A et E permettent de changer de niveau, c'est-à-dire d'entrer dans les sous-menus et en sortir. Le menu le plus global est composé des trois zones d'affichages : le menu de gauche ; le carré central ; et l'affichage de droite. Tu peux passer de l'une à l'autre avec les touches Q et D, qui correspondent aux déplacements dans les listes horizontales.",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1.1.1.1":"Après avoir commencé le dialogue, c'est tout simple. Tu dois choisir de quoi tu veux discuter, et ce que tu veux demander.",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.1.1.1.1":"Et je suppose que Z et S me déplacent dans les listes verticales... Et ensuite, une fois que j'ai sélectionné, par exemple, la zone de gauche ?",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Je peux demander tout ce que je veux ?",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.1.1.1.1.1":"Tu peux utiliser la touche A pour entrer dans la zone de gauche, qui comprend trois sous-zones : en haut, tes informations avec tes points de vie et de mana ;  en dessous, ton iventaire ; et enfin ta classe, qui répertorie tes sous-classes et tes skills.",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Presque. Mais pas sûr que tu sois exaucé...",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.1.1.1.1.1":"Pour rentrer dans l'inventaire par exemple, c'est encore A ?",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Ah... Zut.",
    "dialogue2reponse1.1.1.1.1.2.1.1.1.1.1.1.1.1.1":"Exactement. L'inventaire est lui-même organisé en catégories, qui contiennent les listes d'items. Une fois que tu as sélectionné un item, tu peux appuyer sur Espace pour l'utiliser, si c'est une potion, un parchemin ou un équippement. Puis tu peux ressortir de chaque niveau en appuyant sur E.",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Dans le cas des salles peu spacieuses, tu pourrais demander aux supports de rester à l'écart et à l'abri, puisqu'ils peuvent aider à distance. Ensuite, tu peux les rappeler de loin.",
    "dialogue2phrase1.1.1.1.1.2.1.1.1.1.1.1.1.1.1":"Donc si je veux utiliser un élément sélectionné avec les touches de zones, j'appuie sur Espace. Et pour rappeler mes alliés de loin, dans quelle zone je dois aller ?",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Attends... les rappeler de loin ? Comment je fais ça ?",
    "dialogue2phrase1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Avec les touches de zone !",
    "dialogue2reponse1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1":"Encore ? Et donc, dans quelle zone je dois aller ?",
    "dialogue-1phrase1":"Mes talents sont-ils requis ?",
    "dialogue-1reponse1.1":"J'ai besoin que tu ailles quelque part.",
    "dialogue-1reponse1.2":"On peut discuter ?",
    "dialogue-1reponse1.3":"Est-ce que tu pourrais placer une magie sur un parchemin ?",
    "dialogue-1reponse1.4":"Tu peux me faire un item ?",
    "dialogue-1reponse1.5":"Non merci, c'est suffisant.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1phrase1.3":"Bien sûr. Quelle magie veux-tu ?",
    "dialogue-1phrase1.3refus":"On dirait que tu n'as pas de parchemin vierge... Je peux faire autre chose ?",
    "dialogue-1phrase1.4":"Bien sûr, quoi ?",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1reponse1.4.1":"Parchemin vierge",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Ok. Je peux faire autre chose ?",
    "dialogue-1phrase1.3.1":"Je peux faire autre chose ?",
    "dialogue-1phrase1.3.1echec":"Je n'ai pas assez de mana pour cette magie... Je peux faire autre chose ?",
    "dialogue-1phrase1.4.1":"Voilà. Tu veux que j'y impregne une magie ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1reponse1.4.1.1":"Oui, s'il te plait.",
    "dialogue-1reponse1.4.1.2":"Non merci.",
    "dialogue-1phrase1.1.1.2":"C'est noté. Tu as besoin d'autre chose ?",
    "dialogue-2phrase1":"Qu'est-ce qu'il y a, le mioche ?",
    "dialogue-2reponse1.1":"Tu ne voudrais pas rejoindre notre groupe ? Pour ta propre sécurité.",
    "dialogue-2reponse1.2":"Désolé pour mon comportement.",
    "dialogue-2phrase1.1":"Non merci, je me débrouille très bien tout seul.",
    "dialogue-2phrase1.2":"Je vais laisser passer pour cette fois.",
    "dialogue-2reponse1.1.1":"Comme tu voudras.",
    "dialogue-2reponse1.1.2":"Ne t'étonne pas de mourir !",
    "dialogue-2reponse1.2.1":"Du coup, est-ce que tu voudrais rejoindre notre groupe ?",
    "dialogue-2phrase1.2.1":"Pourquoi pas. On est plus forts à plusieurs.",
    "dialogue-2reponse1.2.1.1":"Bienvenu. Et encore désolé."} #À compléter avec plus de répliques
