global REPLIQUES_PEUREUSE
REPLIQUES_PEUREUSE = {
    "dialogue1phrase1":"Bonjour !",
    "dialogue1reponse1.1":"Salut...",
    "dialogue1reponse1.2":"Bonjour ma jolie.",
    "dialogue1phrase1.1":"",
    "dialogue1phrase1.2":"Ne me parle pas si familièrement.",
    "dialogue1reponse1.1.1":"...qu'est-ce que tu fais ici ?",
    "dialogue1reponse1.1.2":"...où est la sortie ?",
    "dialogue1reponse1.2.1":"Désolé...",
    "dialogue1reponse1.2.2":"Allez, fais pas ta timide...",
    "dialogue1phrase1.1.1":"Je voudrais continuer, mais il y a des monstres sur le chemin.",
    "dialogue1phrase1.1.2":"Tout en haut.",
    "dialogue1phrase1.2.2":"Sérieusement, t'es lourd ! J'ai déjà un copain, [insérer le nom du copain ici], alors arrête !",
    "dialogue1reponse1.1.1.1":"Tu veux que je les tue pour toi ?",
    "dialogue1reponse1.1.1.2":"Des monstres ? Ils sont dangereux ?",
    "dialogue1reponse1.1.2.1":"Pourquoi tu n'y vas pas ?",
    "dialogue1phrase1.1.1.1":"S'il te plaît !",
    "dialogue1phrase1.1.1.2":"Un peu. C'est surtout que je suis fragile...",
    "dialogue1phrase1.1.2.1":"Il y a des monstres sur le chemin.",
    "dialogue1reponse1.1.1.1.1":"Euh... comment on fait pour combattre ?",
    "dialogue1reponse1.1.1.1.2":"Laisse-moi faire.",
    "dialogue1reponse1.1.1.2.1":"Je vais essayer de les combattre.",
    "dialogue1reponse1.1.1.2.2":"Pff... les faibles n'ont qu'à mourir.",
    "dialogue1phrase1.1.1.1.1":"Tu peux donner un coup de pied au sol avec la touche P, je suppose.",
    "dialogue1phrase1.1.1.2.1":"Tu sais faire ?",
    "dialogue1reponse1.1.1.1.1.1":"Un coup de pied au sol ? Ça n'a pas l'air très efficace.",
    "dialogue1reponse1.1.1.1.1.2":"D'accord, je vais y aller.",
    "dialogue1reponse1.1.1.2.1.1":"Oui.",
    "dialogue1reponse1.1.1.2.1.2":"Euh, non...",
    "dialogue1phrase1.1.1.1.1.1":"Je suppose que tu pourrais utiliser ta lance avec X, mais vu son état ça sera encore moins efficace.",
    "dialogue1phrase1.1.1.1.1.2":"Je peux venir avec toi ?",
    "dialogue1reponse1.1.1.1.1.2.1":"Oui, viens.",
    "dialogue1reponse1.1.1.1.1.2.2":"Non, tu ne ferais que me gêner.",
    "dialogue2phrase1":"Ouf, ce gobelin est mort !",
    "dialogue2reponse1.1":"Oui ! Mais il nous a blessés...",
    "dialogue2reponse1.2":"Pff, trop facile !",
    "dialogue2reponse1.3":"Je n'ai pas tout compris...",
    "dialogue2phrase1.1":"Heureusement, nos blessures se soignent avec le temps.",
    "dialogue2reponse1.1.1":"Ah, tu me rassures. En route alors !",
    "dialogue2reponse1.1.2":"Ouf ! Mais, je ne suis pas sûr d'avoir compris tout ce qui s'est passé.",
    "dialogue2phrase1.3":"Qu'est-ce que tu n'as pas compris ?",
    "dialogue2reponse1.3.1":"Comment est-ce que le gobelin est mort ?",
    "dialogue2reponse1.3.2":"C'était quoi, tous les trucs qu'on voyait ?",
    "dialogue2reponse1.3.3":"Pourquoi est-ce qu'il reste quelque chose ?",
    "dialogue2phrase1.3.1":"Il avait une barre rouge au-dessus de la tête, comme toi et moi. Cette barre représente ses PVs, et chacune de tes attaques lui a fait perdre des PVs. Quand ses PVs ont atteint 0, il est mort.",
    "dialogue2phrase1.3.2":"Les marques marrons représentaient les attaques. Il y avait aussi des points rouges à chaque fois que quelqu'un se faisait blesser. Et s'il y avait des espèces de cercles oranges sous tes pieds, c'étaient mes magies de boost. Tu as peut-être pu voir que j'avais moi-même un cercle bleu à chaque fois que je lançais une magie.",
    "dialogue2phrase1.3.3":"Le corps du gobelin n'allait pas disparaître ! Son cadavre est toujours là. C'est dégoutant, mais il y a aussi les items qu'il transportait, en l'occurence son équippement.",
    "dialogue2reponse1.3.1.1":"Merci, c'est tout ce que je voulais savoir !",
    "dialogue2reponse1.3.1.2":"Il y a autre chose que je n'ai pas compris.",
    "dialogue3phrase1":"Ouf ! Il était coriace, celui-là !",
    "dialogue3reponse1.1":"C'est peu de le dire ! Qu'est-ce que c'était que ces attaques à distance !?",
    "dialogue3reponse1.2":"Mais non, c'était facile !",
    "dialogue3phrase1.1":"De la magie. Heureusement qu'il ne peut plus s'en servir quand il tombe à court de mana.",
    "dialogue3reponse1.1.1":"Tu es une magicienne, non ? Tu peux utiliser ce genre de sorts ?",
    "dialogue3reponse1.1.2":"Effectivement, ce serait infernal sinon !",
    "dialogue3phrase1.1.1":"Je suis juste une magicienne de soutien, je n'ai pas de sorts d'attaque. Mais je peux doubler tes dégats, et je n'ai même pas besoin de me mettre en danger en première ligne, c'est pas génial ?",
    "dialogue3reponse1.1.1.1":"C'est comme si j'étais deux fois plus nombreux ! Merci pour ton aide.",
    "dialogue3reponse1.1.1.2":"Pff, inutile...",
    "dialogue4phrase1":"Nous nous rapprochons du camp gobelin, il serait bien que je t'explique quelques trucs sur les monstres.",
    "dialogue4reponse1.1":"Oui, volontiers.",
    "dialogue4reponse1.2":"C'est gentil de proposer, mais je n'ai pas besoin d'aide.",
    "dialogue4reponse1.3":"Tu me prends pour un débutant ? Tu crois que je ne connais pas les monstres ?",
    "dialogue4phrase1.1":"Les monstres sont très différents les uns des autres, aussi bien par leurs comportements que par leurs capacitées.",
    "dialogue4phrase1.2":"D'accord, bonne chance.",
    "dialogue4phrase1.3":"Ne viens pas te plaindre si tu meurs !",
    "dialogue4reponse1.1.1":"Donc, ils ne vont pas tous attendre sans bouger comme celui de l'étage précédent ?",
    "dialogue4reponse1.1.2":"Leurs capacitées ? Tu veux dire leur puissance de combat ?",
    "dialogue4reponse1.2.1":"",
    "dialogue4phrase1.1.1":"Exactement. Celui-là était une sentinelle, qui ne bougent que quand il aperçoit un ennemi.",
    "dialogue4phrase1.1.2":"Entre autre, mais je pensais plutôt aux capacités comme le soin, ou les attaques magiques.",
    "dialogue4reponse1.1.1.1":"Attendre qu'on vienne à eux est donc plutôt une exception ?",
    "dialogue4reponse1.1.1.2":"Est-ce qu'il y a d'autres monstres que des gobelins ici ?",
    "dialogue4reponse1.1.2.1":"Ils peuvent même utiliser des magies de soin ?",
    "dialogue4phrase1.1.1.1":"Oui. C'est encore plus rare chez les monstres non-humanoïdes comme les slimes.",
    "dialogue4phrase1.1.1.2":"IL y a les gobelins, les orcs, les slimes, les ombriuls... certains ne sont pas hostiles aux humains, et ne combattront que si on les provoque.",
    "dialogue4phrase1.1.2.1":"Les humanoïdes comme les gobelins comptent des mages très variés dans leurs rangs.",
    "dialogue4reponse1.1.1.1.1":"Il existe différentes espèces de monstres ?",
    "dialogue4reponse1.1.1.1.2":"Et qu'est-ce que tu disais sur leurs capacités ?",
    "dialogue4reponse1.1.2.1.1":"Donc ils ont des rôles spécifiques...",
    "dialogue4reponse1.1.2.1.2":"Et les monstres non-humanoïdes ?",
    "dialogue4phrase1.1.1.1.2":"Certains ont une meilleure défense, ou une bonne vitesse, d'autres peuvent même utiliser de la magie pour attaquer ou soigner.",
    "dialogue4phrase1.1.2.1.1":"Exactement. La sentinelle qu'on a croisée à l'étage précédent est spécialisée en défense et ne se déplace que quand elle aperçoie un ennemi, alors que d'autres nous cherchent activement.",
    "dialogue4phrase1.1.2.1.2":"Ils souvent tous identiques au sein d'une espèce. Il est aussi plus rare de les voir en groupe. Parfois les humanoïdes les dressent pour le combat.",
    "dialogue4reponse1.1.1.1.2.1":"Et il faut qu'on combatte tout ça ? Ah, la galère...",
    "dialogue4reponse1.1.1.1.2.2":"Et bien, nous aussi, donc on s'en sortira !",
    "dialogue4reponse1.1.2.1.1.1":"Pourquoi faut-il qu'ils nous en veuillent tous...",
    "dialogue4reponse1.1.2.1.1.2":"Ces gobelins sont bien organisés.",
    "dialogue4phrase1.1.1.1.2.1":"Hélas...",
    "dialogue4phrase1.1.1.1.2.2":"Oui ! Je te fais confiance !",
    "dialogue4phrase1.1.2.1.1.1":"La plupart des monstres ont une dent contre les humains, mais pas tous. Il arrive même qu'ils se battent entre espèces.",
    "dialogue4phrase1.1.2.1.1.2":"C'est peut-être parce qu'ils ont un chef ? Les orcs sont un peu pareil.",
    "dialogue4reponse1.1.1.1.2.1.1":"Bon, allons-y.",
    "dialogue4reponse1.1.2.1.1.1.1":"Il y a beaucoup d'espèces de monstres dans ce labyrinthe ?",
    "dialogue4reponse1.1.2.1.1.2.1":"Je vois... Bon, allons-y.",
    "dialogue4phrase1.1.2.1.1.1.1":"Je ne sais pas, et j'espère en croiser le moins possible...",
    "dialogue4reponse1.1.2.1.1.1.1.1":"Ne t'inquiète pas, je te protégerai.",
    "dialogue4reponse1.1.2.1.1.1.1.2":"On verra bien. Allons-y.",
    "dialogue4phrase1.1.2.1.1.1.1.1":"Merci !",
    "dialogue5phrase1":"Est-ce que tu vois ces portes dans les murs autour de toi ?",
    "dialogue5reponse1.1":"Oui.",
    "dialogue5reponse1.2":"Ces barres oranges ?",
    "dialogue5reponse1.3":"Évidemment, je ne suis pas aveugle !",
    "dialogue5phrase1.1":"Il te faut des clés pour les ouvrir.",
    "dialogue5phrase1.2":"C'est ça. Il te faut des clés pour les ouvrir.",
    "dialogue5reponse1.1.1":"Des clés ? Où est-ce que je peux les trouver ?",
    "dialogue5phrase1.1.1":"Par terre, après avoir tué un monstre par exemple. Ramasse-les avec la touche M.",
    "dialogue5reponse1.1.1.1":"Ok, je regarderai autour de moi.",
    "dialogue5phrase1.1.1.1":"Attends ! J'en ai une, elle te sera peut-être utile.",
    "dialogue5reponse1.1.1.1.1":"Merci. J'y vais alors.",
    "dialogue5reponse1.1.1.1.2":"Comment tu l'as trouvée ?",
    "dialogue5phrase1.1.1.1.2":"Un des gobelins l'a laissée tomber quand ils ont capturé mon petit-ami.",
    "dialogue5reponse1.1.1.1.2.1":"Tu crois qu'il est enfermé ici ? Je vais le libérer.",
    "dialogue-1phrase1":"Tu as besoin de quelque chose ?",
    "dialogue-1reponse1.1":"Tu pourrais aller quelque part ?",
    "dialogue-1reponse1.2":"Discutons un peu.",
    "dialogue-1reponse1.3":"Est-ce que tu pourrais placer une magie sur un parchemin ?",
    "dialogue-1reponse1.3":"Ce sera tout pour l'instant, merci.",
    "dialogue-1phrase1.1":"Où ?",
    "dialogue-1phrase1.2":"On a pas vraiment le temps, là...",
    "dialogue-1phrase1.3":"Bien sûr. Quelle magie veux-tu ?",
    "dialogue-1phrase1.3refus":"On dirait que tu n'as pas de parchemin vierge... Tu as besoin d'autre chose ?",
    "dialogue-1reponse1.1.1":"Tu peux suivre quelqu'un ?",
    "dialogue-1reponse1.1.2":"Tu vois là-bas ?",
    "dialogue-1reponse1.1.3":"Cherche la sortie.",
    "dialogue-1reponse1.2.1":"Ah, c'est vrai.",
    "dialogue-1reponse1.3.1":"Qu'est-ce que tu as ?",
    "dialogue-1phrase1.1.1":"Oui, qui ?",
    "dialogue-1phrase1.1.3":"Ok. Tu as besoin d'autre chose ?",
    "dialogue-1phrase1.3.1":"Tu as besoin d'autre chose ?",
    "dialogue-1phrase1.3.1echec":"Je n'ai pas assez de mana pour cette magie... Tu as besoin d'autre chose ?",
    "dialogue-1reponse1.1.1.1":"Moi.",
    "dialogue-1reponse1.1.1.2":"Je vais te montrer.",
    "dialogue-1phrase1.1.1.2":"C'est noté. Tu as besoin d'autre chose ?",
    "dialogue-2phrase1":"Tu as du culot de revenir me parler après ce que tu m'as dit !",
    "dialogue-2reponse1.1":""} #À compléter avec plus de répliques
