#Un fichier avec des constantes d'équilibrage.
#Pour modifier facilement l'équilibrage.


#Quelques constantes qui affectent tout le monde :
LATENCE_DEPLACEMENT =
LATENCE_COURSE =
LATENCE_STOMP =
LATENCE_ATTAQUE =
TAUX_STOMP =
TAUX_ATTAQUE =


#Les constantes du joueur :
FORCE_HEROS =
VITESSE_HEROS =
PV_HEROS =
REGEN_HEROS =


#Queqlues constantes qui affectent plein de gobelins
TAUX_LANCE =
TAUX_EPEE =
TAUX_CIMETERE =
TAUX_ARMURE_SENT =
TAUX_HAUME =
TAUX_ARMURE_GUER =
MANA_BANDEAU =


#Les constantes du premier monstre :
FORCE_PREMIER =
VITESSE_PREMIER =
PV_PREMIER =

#Les constantes du deuxième monstre :
VITESSE_DEUXIEME =
PV_DEUXIEME =
PM_DEUXIEME =
REGEN_DEUXIEME =

#Les constantes du paumé :
FORCE_PAUME =
VITESSE_PAUME =
PV_PAUME =
REGEN_PAUME =
TAUX_TUNIQUE =

#Les constantes de la peureuse :
FORCE_PEUREUSE =
VITESSE_PEUREUSE =
PV_PEUREUSE =
REGEN_PEUREUSE =
PM_PEUREUSE =
REGEN_PM_PEUREUSE =
REGEN_PM_ROBE =
PM_BOOST =
TAUX_BOOST =
LATENCE_BOOST =
PM_MULTI_BOOST =
TAUX_MULTI_BOOST
LATENCE_MULTI_BOOST

#Les constantes du troisième monstre :
FORCE_TROISIEME =
VITESSE_TROISIEME =
PV_TROISIEME =

#Les constantes des sentinelles :
FORCE_SENT =
VITESSE_SENT =
PV_SENT =

#Les constantes des guerriers :
FORCE_GUER =
VITESSE_GUER =
PV_GUER =

#Les constantes de l'encombrant :
FORCE_ENCOMBRANT =
TAUX_EPEE_ENCOMBRANT =
VITESSE_ENCOMBRANT =
PV_ENCOMBRANT =
REGEN_ENCOMBRANT =
TAUX_ARMURE_ENCOMBRANT =

#Les constantes de l'alchimiste :
FORCE_ALCHIMISTE =
VITESSE_ALCHIMISTE =
PV_ALCHIMISTE =
REGEN_ALCHIMISTE =
PM_ALCHIMISTE =
REGEN_PM_ALCHIMISTE =
REGEN_PM_TUNIQUE =
COUT_SECOUSSE =
DEGATS_SECOUSSE =
PORTEE_SECOUSSE =
LATENCE_SECOUSSE =

#Les constantes des mages :
PV_MAGE =
VITESSE_MAGE =
PM_MAGE =
COUT_MAGE =
DEGATS_MAGE =
LATENCE_MAGE =
REGEN_MAGE =

#Les constantes des shamans :
PV_SHAMAN =
VITESSE_SHAMAN =
PM_SHAMAN =
REGEN_SHAMAN =

#Les constantes de la peste :
FORCE_PESTE =
VITESSE_PESTE =
PV_PESTE =
REGEN_PESTE =
PM_PESTE =
REGEN_PM_PESTE =
DEGATS_SOUTANE =
PM_SOIN =
PV_SOIN =
LATENCE_SOIN =
PM_MULTI_SOIN =
PV_MULTI_SOIN
LATENCE_MULTI_SOIN

#Les constantes de la bombe atomique :
FORCE_BOMBE =
VITESSE_BOMBE =
PV_BOMBE =
REGEN_BOMBE =
PM_BOMBE =
REGEN_PM_BOMBE =
REGEN_PM_ROBE_SORCIERE =
REGEN_PM_CHAPEAU_SORCIERE =
COUT_VOLCAN =
DEGATS_VOLCAN =
PORTEE_VOLCAN =
LATENCE_VOLCAN =

#Les constantes des gobelins de base :
FORCE_GOB =
VITESSE_GOB =
PV_GOB =

#Les constantes du marchand :
FORCE_MARCHAND =
TAUX_EPEE_MARCHAND =
VITESSE_MARCHAND =
PV_MARCHAND =
REGEN_MARCHAND =
TAUX_ARMURE_MARCHAND =

#Les constantes des gobelins de base :
FORCE_CHEF =
VITESSE_CHEF =
PV_CHEF =
REGEN_CHEF =

#Les constantes du receptionniste :
FORCE_RECEPTIONNISTE =
VITESSE_RECEPTIONNISTE =
PV_RECEPTIONNISTE =
REGEN_RECEPTIONNISTE =
