from .Magie import *
from .Magies_attaque.Attaques_corps_a_corps import *
from .Magies_attaque.Attaques_distance import *
from .Magies_attaque.Boosts import *
from .Magies_attaque.Poings_magiques import *
from .Magies_diverses import *
from .Magies_economie import *
from .Magies_enchantement import *
from .Magies_projectiles import *
from .Magies_soin import *