from Jeu.Effet.Attaques import *
from Jeu.Effet.Auras import *
from Jeu.Effet.Blocages import *
from Jeu.Effet.Deplacements import *
from Jeu.Effet.Effets_divers import *
from Jeu.Effet.Effets_protection import *
from Jeu.Effet.Enchantements import *
from Jeu.Effet.Magies import *
from Jeu.Effet.Maladies import *