from Jeu.Entitee.Agissant.Humain.Alchimiste import*
from Jeu.Entitee.Agissant.Humain.Bombe_atomique import*
from Jeu.Entitee.Agissant.Humain.Codeur import*
from Jeu.Entitee.Agissant.Humain.Encombrant import*
from Jeu.Entitee.Agissant.Humain.Heros import*
from Jeu.Entitee.Agissant.Humain.Marchand import*
from Jeu.Entitee.Agissant.Humain.Paume import*
from Jeu.Entitee.Agissant.Humain.Peste import*
from Jeu.Entitee.Agissant.Humain.Peureuse import*
from Jeu.Entitee.Agissant.Humain.Receptionniste import*