from .attaquant_magique_agissant import *
from .attaquant_magique_case import *
from .attaquant_magique_poing import *
from .bourrin import *
from .dps import *
from .fuyard import *
from .mage import *
from .multi_renforceur import *
from .multi_soigneur import *
from .renforceur import *
from .sentinelle import *
from .soigneur import *
from .stratege import *
from .support import *
from .support_lointain import *
from .tank import *