from .Attaquant_magique_case import *
from .Bourrin import *
from .Dps import *
from .Fuyard import *
from .Mage import *
from .Multi_renforceur import *
from .Multi_soigneur import *
from .Multi_soigneur_protecteur import *
from .Renforceur import *
from .Sentinelle import *
from .Soigneur import *
from .Stratege import *
from .Support import *
from .Support_lointain import *
from .Tank import *