from ..Entitee.Agissant.Role.Attaquant_magique_case import *
from ..Entitee.Agissant.Role.Bourrin import *
from ..Entitee.Agissant.Role.Dps import *
from ..Entitee.Agissant.Role.Fuyard import *
from ..Entitee.Agissant.Role.Mage import *
from ..Entitee.Agissant.Role.Multi_renforceur import *
from ..Entitee.Agissant.Role.Multi_soigneur import *
from ..Entitee.Agissant.Role.Multi_soigneur_protecteur import *
from ..Entitee.Agissant.Role.Renforceur import *
from ..Entitee.Agissant.Role.Sentinelle import *
from ..Entitee.Agissant.Role.Soigneur import *
from ..Entitee.Agissant.Role.Stratege import *
from ..Entitee.Agissant.Role.Support import *
from ..Entitee.Agissant.Role.Support_lointain import *
from ..Entitee.Agissant.Role.Tank import *