from Old_Jeu.Dialogues.Dialogues_receptionniste import *
from Old_Jeu.Dialogues.Dialogues_paume import *
from Old_Jeu.Dialogues.Dialogues_peureuse import *
from Old_Jeu.Dialogues.Dialogues_codeur import *
from Old_Jeu.Dialogues.Dialogues_encombrant import *
from Old_Jeu.Dialogues.Dialogues_alchimiste import *
from Old_Jeu.Dialogues.Dialogues_peste import *
from Old_Jeu.Dialogues.Dialogues_bombe_atomique import *
from Old_Jeu.Dialogues.Dialogues_marchand import *
