from Jeu.Effet.Magie.Magie import *
from Jeu.Effet.Magie.Magies_attaque.Attaques_corps_a_corps import *
from Jeu.Effet.Magie.Magies_attaque.Attaques_distance import *
from Jeu.Effet.Magie.Magies_attaque.Boosts import *
from Jeu.Effet.Magie.Magies_attaque.Poings_magiques import *
from Jeu.Effet.Magie.Magies_diverses import *
from Jeu.Effet.Magie.Magies_economie import *
from Jeu.Effet.Magie.Magies_enchantement import *
from Jeu.Effet.Magie.Magies_projectiles import *
from Jeu.Effet.Magie.Magies_soin import *